### ISSUE TITLE
handle on_captcha_received 

### ISSUE THREAD

**Issue by pilipranks** [tomer8007/kik-bot-api-unofficial#102]
Hi, after send message i receive on_captcha_received callback, but how could i handle it? send_chat_message method dosnt have captcha argument. disconnect and relogin works half the time.

**Comment by tomer8007** [comment]
The callback includes a `captcha_url` memeber. If you want to solve it each time manually you'd probably want to launch the browser with this URL  and grab the results (that means to intercept the request to `https://kik.com/captcha-url` and get the response parameter).

Then, to solve the captcha you can call `send_captcha_result` with the response you got.

BTW, What about your [socks proxy issue](https://github.com/tomer8007/kik-bot-api-unofficial/issues/99) ?

**Comment by pilipranks** [comment]
thanks, try it. captcha may be solving in automatic mode.

**Comment by tomer8007** [comment]
Also take a look at the documentation of the method [send_captcha_result](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L367).
