### ISSUE TITLE
Get JID from username?

### ISSUE THREAD

**Issue by CasperYep** [tomer8007/kik-bot-api-unofficial#103]
I am trying to get someone's jid from a username so I can add them, Been trying for a few hours now and can't figure anything out.

**Comment by tomer8007** [comment]
I think what you're looking for is [request_info_of_username](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L210).

**Comment by CasperYep** [comment]
I tried this before but got this error,

def Add_Username(username):
    KikClient.request_info_of_username(username, username)

Add_Username("Name")

`Traceback (most recent call last):
  File "D:\Coding\KIK-BOT\Main.py", line 54, in <module>
    Add_Username("Name")
  File "D:\Coding\KIK-BOT\Main.py", line 52, in Add_Username
    KikClient.request_info_of_username(username, username)
  File "C:\Users\perca\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial\client.py", line 211, in request_info_of_username
    return self._send_xmpp_element(roster.FriendRequest(username))
AttributeError: 'str' object has no attribute '_send_xmpp_element'`

**Comment by tomer8007** [comment]
Did you take a look at the [echo_bot.py](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/examples/echo_bot.py) example? You have to subcalss `KikClientCallback`, create an instance of `KikClient`, then call this method on the instance.

After that your infomration should be returned in one of the callbacks, maybe `on_peer_info_received`, `on_friend_attribution` or so.

**Comment by tomer8007** [comment]
**UPDATE**: There is now a dedicated method for this: [get_jid](https://github.com/tomer8007/kik-bot-api-unofficial/blob/d0f75ba149959101b23b0b3a14048898a11ff01a/kik_unofficial/client.py#L637)

**Comment by Mortalgodz** [comment]
Hey Tomer, im really new to programming 
I have a JID which I would like to decrypt to the corresponding username so I can just send out a chat request. Can I reach out to your active bot on kik app or I would have to go through a process.

Can you kindly guide me thanks.

**Comment by tomer8007** [comment]
@Mortalgodz I think `request_info_of_username` should do it. Please try these methods first.

**Comment by Mortalgodz** [comment]
where do i do it though .. whats the software platform no clue
