### ISSUE TITLE
Unknown message type

### ISSUE THREAD

**Issue by CarbonNeuron** [tomer8007/kik-bot-api-unofficial#11]
Hey! It's me again. I'm working with the bot, I want to make it so whenever someone joins the group, it will send the rules! Whenever I do this however, I get an error

**Comment by CarbonNeuron** [comment]
My error is a unknown message type

**Comment by tomer8007** [comment]
Hmm. How do you get notified when someone joins a group? Maybe that's the uknown message type. Paste it here.

**Comment by CarbonNeuron** [comment]
Will do when I get home from school. Thanks for the fast replys,I really appreciate it!

**Comment by CarbonNeuron** [comment]
Essentially, from what I remember from my cost, I get new event, and the elements xml content contained status jid + get the 15 slice in a string, joined, to know if someone joined, and what their name was

**Comment by tomer8007** [comment]
Sounds good for the wiki

**Comment by CarbonNeuron** [comment]
Also, I wrote those modules for the group admin functions, it's really repetitive and doesn't really need to be added to GitHub, in my opinion.

**Comment by tomer8007** [comment]
Why not? functions like `ban` and `unab` are good features for the API. I intended to write them anyway

**Comment by CarbonNeuron** [comment]
I'll send the code for them after class. Just the modules are really small. I haven't figured out a way to find if they succeeded or failed.

**Comment by tomer8007** [comment]
Did you test them?

**Comment by CarbonNeuron** [comment]
They do work, yes they ban and unban users. Along with removing and adding, if you are friends with the user.

**Comment by tomer8007** [comment]
This is great then. Do you say they return the same response for success and failure?
