### ISSUE TITLE
Is it known why client_legacy.py gets no response from kik

### ISSUE THREAD

**Issue by ghost** [tomer8007/kik-bot-api-unofficial#114]
I found legacy's code more readable, and after fixing up a few syntax errors and changing the Android id to not get a ban message, it logs in fine. I can receive messages but upon requesting the roster Kik closes the connection.
This is also an issue with the C# sidekik API and this always happened with my own C Kik api

Is there anything that was changed between the client and client_legacy that fixed this?
 Client.py works for me just fine

**Comment by tomer8007** [comment]
Yes, I agree the legacy client's code can be more redable - abstraction and modularity often has the cost of complexity.

Unfortunately these unexpected connection-closing problems are usually hard to understand. I also don't quite remember a specific change. Are you able to send messages? Can you mimic the `client.py`?

**Comment by ghost** [comment]
To be more specific, the only thing that gets a response is ping, which gets pong

Anything else, from roster request to sending message, info for username, etc:
Disconnected (Kik server returns empty response)

I'm going to start a new C api based off the client.py
