### ISSUE TITLE
Help Server

### ISSUE THREAD

**Issue by gastrodon** [tomer8007/kik-bot-api-unofficial#117]
Is there a server (perhaps a kik group chat or discord guild) where I can ask small questions that are not necessarily worthy of their own issue?

**Comment by tomer8007** [comment]
I heard @Jaapp [ created a public kik group specifically for this project](https://github.com/tomer8007/kik-bot-api-unofficial/issues/18#issuecomment-353806799)  with the tag #kikbotapi, back in the end of 2017.
@Jaapp- Is is still there?

**Comment by gastrodon** [comment]
Yep, found it and joined. Thanks
