### ISSUE TITLE
Unable to send delivered receipts

### ISSUE THREAD

**Issue by gastrodon** [tomer8007/kik-bot-api-unofficial#118]
Messages being marked as "delivered" with `client.send_delivered_receipt()` method are not marked as delivered when viewing the message on the senders end using the most recent version of the kik app.

Note that `clientsend_read_receipt()` appears to be working as intended with the same parameters, when testing with the same message. 

Code in question, as part of an implementation with flask:
```python
@app.route("/update_delivered", methods = ["POST"])
def update_delivered():
    payload = json.loads(request.data)
    app.client.send_delivered_receipt(payload["jid"], payload["id"])
    return json.dumps({"Message" : f"Message {payload['id']} was marked as delivered"})

@app.route("/update_read", methods = ["POST"])
def update_read():
    payload = json.loads(request.data)
    app.client.send_read_receipt(payload["jid"], payload["id"], group_jid = payload.get("group_jid", None))
    return json.dumps({"Message": f"Message {payload['id']} was marked as read"})
```

When I log the result of either function to the terminal, it appears to return the intended value of the same message id, so this leads me to believe that there might be a problem with how the data is being transmitted.

**Comment by tomer8007** [comment]
Looking at [OutgoingReadReceipt](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/xmpp/chatting.py#L154) and [OutgoingDeliveredReceipt](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/xmpp/chatting.py#L175), I can see that the only difference in the transmitted data is the ` type=` element, so that's quite odd.

**Comment by gastrodon** [comment]
I will try to use [charles](https://charlesproxy.com) to sniff and see if there is some discrepancy between my computer talking to kik and one of the apps, though I will need to learn some more to do that. It might also be the case that I'm calling something incorrectly in the above, but I'm able to reproduce this by calling the same methods from other sources (ie command line)

**Comment by bluemods** [comment]
kik uses 'QOS' in the receipt message instead of 'type="delivered"' to send delivered receipts, and kik translates them into it saying type="delivered" when you recieve the stanza.

Example delivered receipt stanza (outgoing):

<message type="receipt" id="8eef091b-7d13-48c6-bb89-78bfa8af5688" to="(JID here)@talk.kik.com" cts="1563485748593"><kik push="false" qos="true" timestamp="1563485748593" /><receipt xmlns="kik:message:receipt"><msgid id="5eb0558d-e6e5-493b-a592-3bc83c4c3129" /></receipt></message>

**Comment by bluemods** [comment]
Very easy to send a delivered receipt!

The stanza:

```<iq type=\"set\" id=\"{1}\" cts=\"{2}\"><query xmlns=\"kik:iq:QoS\"><msg-acks><sender jid=\"{3}\"{4}><ack-id receipt=\"true\">{5}</ack-id></sender></msg-acks><history attach=\"false\" /></query></iq>```

1 = Crypto UUID
2 = Unix timestamp
3 = The correspondent that sent the message (always is the ```from``` attribute)
4 = *IF* it is a group, the group jid goes here acquired from the ```g``` tag. If not a group this is left blank. 
5 = The message id we are sending a delivered receipt for.

Clarification for {4}: 

If it's a PM, sender tag looks like this:

```<sender jid="kikteam@talk.kik.com">```

If a group, sender tag looks like this:

```<sender jid="kikteam@talk.kik.com" g="1234567890_g@groups.kik.com">```

The ```receipt``` attribute is what ends up sending the delivered receipt. If you change that to ```false``` it will just ack the message but not send a delivered receipt to the user.

**Comment by tomer8007** [comment]
@bluemods Interesting, are you successfully using this stanza to send devilevered receipts using the the API?

**Comment by bluemods** [comment]
I use a private API that I made in Java, but yeah, I double checked it worked before posting this

**Comment by HeavenHeal** [comment]
> I use a private API that I made in Java, but yeah, I double checked it worked before posting this

just tried and it keep failing to send the Delivered receipt also i've double checked the stanza using logcat and it matched what u have posted

**Comment by bluemods** [comment]
> > I use a private API that I made in Java, but yeah, I double checked it worked before posting this
> 
> just tried and it keep failing to send the Delivered receipt also i've double checked the stanza using logcat and it matched what u have posted

Give me a bit to learn python and set it up on a VM since I can't figure out how to run python on windows and I'll update you with a source code answer

**Comment by MisterWorld** [comment]
> just tried and it keep failing to send the Delivered receipt also i've double checked the stanza using logcat and it matched what u have posted

i tried too and it keep failing 

**tomer8007**, Have you tried the stanzа, which **bluemods**  had proposed?

**Comment by tomer8007** [comment]
@MisterWorld Just tried it, and I can't get it to work either. The form that it's in the API did work in the past, though, so they must have changed something.

@bluemods Anything that is different in your Java implementation? I also tried to use crypto timestamp but no luck.

**Comment by bluemods** [comment]
Okay, I don't know how to submit a PR and my python may be bad, but this works for me. If it doesn't for yall let me know.

Don't use the crypto timestamp btw

You're free to remove my comments or whatever, they are just there for clarity.

Change these methods:

chatting.py:


# do not change receipt="true"
```
class OutgoingDeliveredReceipt(XMPPElement):
    def __init__(self, bin_jid, peer_jid, receipt_message_id):
        super().__init__()
        
        self.bin_jid = bin_jid
        self.peer_jid = peer_jid
        self.receipt_message_id = receipt_message_id

    def serialize(self):
        if self.bin_jid and 'groups.kik.com' in self.bin_jid:
            g_tag = " g=\"{}\"".format(self.bin_jid)
        else:
            g_tag = ''
            
        timestamp = str(int(round(time.time() * 1000)))
        data = ('<iq type="set" id="{}" cts="{}">'
                '<query xmlns="kik:iq:QoS">'
                '<msg-acks>'
                '<sender jid="{}"{}>'
                '<ack-id receipt="true">{}</ack-id>'
                '</sender>'
                '</msg-acks>'
                '<history attach="false" />'
                '</query>'
                '</iq>').format(self.message_id, timestamp, self.peer_jid, g_tag, self.receipt_message_id)
        return data.encode()
```

client.py:

```
    def send_delivered_receipt(self, bin_jid: str, peer_jid: str, receipt_message_id: str):
        """
        Fixed by Blue~
        Sends a receipt indicating that a specific message was delivered to another person.

        Also doubles as 'acking' the message
        meaning if a message history request is performed, Kik will *not* redeliver it.

        :param bin_jid: Group JID if a group, same as peer jid if PM
        :param peer_jid: The other peer's JID to send to receipt to
        :param receipt_message_id: The message ID for which to ack and send a delivered receipt for
        """
        log.info(
            "[+] Sending ack / delivered receipt to JID {} for message ID {} in {}".format(peer_jid, receipt_message_id,
                                                                                           bin_jid))
        return self._send_xmpp_element(chatting.OutgoingDeliveredReceipt(bin_jid, peer_jid, receipt_message_id))
```

Example usage:

```
    def on_group_message_received(self, chat_message: chatting.IncomingGroupChatMessage):
        if chat_message.body and chat_message.request_delivered_receipt:
            self.client.send_delivered_receipt(chat_message.group_jid, chat_message.from_jid, chat_message.message_id)

    def on_chat_message_received(self, chat_message: chatting.IncomingChatMessage):
        # send delivered receipt before message
        if chat_message.body and chat_message.request_delivered_receipt:
            self.client.send_delivered_receipt(None, chat_message.from_jid, chat_message.message_id)
            self.client.send_chat_message(chat_message.from_jid, 'You said {}'.format(chat_message.body))
```

**Comment by tomer8007** [comment]
Now it works for me, thank you. This is now [commited in](https://github.com/tomer8007/kik-bot-api-unofficial/commit/091c475e5b0dba6432d50bba2e08c49f0d9334a6).

By the way I think it was just an string formatting problem or so (you started from `{1}` instead of `{0}`)
