### ISSUE TITLE
Can't get a list of members

### ISSUE THREAD

**Issue by Mickyfubu** [tomer8007/kik-bot-api-unofficial#12]
I am trying to get a list of my group but keep getting an unknown message error at every event that would provide the information I need.

**Comment by maritaria** [comment]
Do you mean you are trying to get the list of members of a group you are in?
Could you provide the code you are using to retrieve the info?

**Comment by tomer8007** [comment]
I was able to get information about private group members using this code:
```
partners = kik_client.get_chat_partners()
user_jid = partners['1100220797029_g@groups.kik.com']["users"][1]["jid"]
info_for_user = kik_client.get_info_for_node(user_jid)
```
Make sure you are using the latest version from GitHub.

**Comment by Mickyfubu** [comment]
Works! thanks! I'm also trying to work out a leave PM feature and was wondering if you could help me out with that?

**Comment by tomer8007** [comment]
Well, I don't know this feature of kik, what is it? Do you have the XML representation of the requests?

**Comment by Mickyfubu** [comment]
no no not a kik feature im trying to create a bot that PMs people when they leave. basically just trying to figure out how to get the username of someone as they leave and recognize the event so i can write some code to send them a message.

**Comment by tomer8007** [comment]
Oh, I get it. The XML is on the wiki under "When someone leaves a (public) group your bot is a member of"

**Comment by Mickyfubu** [comment]
is there a method for that like with send_message because this network stuff makes me XMPee-pee my pants

**Comment by tomer8007** [comment]
Shouldn't be too hard, for now if you wanna do it quick & dirty you can search for the words 'has left the group' from `get_next_event()["raw_response"]`, and get the JID by looking for '<status jid=' just before it. It's very clear when you look at the wiki.

**Comment by Mickyfubu** [comment]
incredibly helpful thank you

**Comment by tomer8007** [comment]
Let me know if it worked

**Comment by Mickyfubu** [comment]
worked great actually. pretty nice for a quick and dirty fix
