### ISSUE TITLE
Roster results showing User class instead of Group class

### ISSUE THREAD

**Issue by sapiosaurus** [tomer8007/kik-bot-api-unofficial#122]
Hi, this is a new one. With no code changes, apparently the RosterResponse is returning groups as a User() class with no member attributes. Is this a new kik change?

**Comment by tomer8007** [comment]
Hmm. the code that decides whether a peer is a group or a user is [here](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/xmpp/roster.py#L33). Can you maybe post the raw response you get to the `FetchRosterRequest`?
