### ISSUE TITLE
how kik can detect me ?

### ISSUE THREAD

**Issue by diadka** [tomer8007/kik-bot-api-unofficial#125]
Hey guys.
 I tried to work with kik a half  year ago and it lasted a month. 2 weeks ago I returned again, but now I see the same problem. I cant join groups. I tried to change the ip address and it helped me for 2 days. But now all my attempts do not come to success. The account registered through python join of 12 groups in Nox.  http://prntscr.com/ollwxp  despite the fact that Nox does not pass safetynet check http://prntscr.com/ollv6s
Any ideas? How are your guys working now?

**Comment by sapiosaurus** [comment]
We're not using Nox. This is simply a python API implementation for Kik.

**Comment by diadka** [comment]
thanks for answering. I understand this is just an example of an account registered through the API. In Python, I get a 400 error and try to understand why this happens.
