### ISSUE TITLE
Wondering are there more examples?

### ISSUE THREAD

**Issue by peterarcher** [tomer8007/kik-bot-api-unofficial#13]
Any more examples?

**Comment by tomer8007** [comment]
What do you want to do? I could write a quick example.

**Comment by peterarcher** [comment]
I am trying to send different replies  based on the user's response, sort of like a really basic AI. I have been trying to do it with multiple if statements but with no success.

Thank you for all the work you have done btw

**Comment by tomer8007** [comment]
Isn't it what the echo bot does? And by no success do you mean the messages ado not get sent?
