### ISSUE TITLE
New group member JID and xiphias_get_users

### ISSUE THREAD

**Issue by bryantqo** [tomer8007/kik-bot-api-unofficial#131]
So I am attempting to use the API to prevent young accounts from joining a room. When a user joins that is chatting with the api account I am able to see <username>@talk.kik.com if the account is not chatting with the api account I see something that appears to be either a hash or encrypted value of some sort for example iyyro...snipped...f6v6a_a@talk.kik.com. Furthermore if I use this JID with a xiphias_get_users or request_info_of_jids the response is only a partial success resulting in the display name but not the profile age or thumbnails. Any other info would be appreciated

```
def on_group_status_received(self, response: chatting.IncomingGroupStatus):
        print("[+] Status message in {}: {} from {}".format(response.group_jid, response.status, response.status_jid))

        if response.status.find("has joined the chat") > 0:
            self.client.xiphias_get_users(response.status_jid) #Results in an empty UserResponse
            self.client.request_info_of_jids(response.status_jid) #Results in a partial success having the display name but nothing else
```

**Comment by tomer8007** [comment]
Can you use `xiphias_get_users` correctly on a user that is chatting with the bot?

**Comment by bryantqo** [comment]
Yes it appears so. I will try to get a packet dump later

**Comment by bastianrickmann** [comment]
The user has a public_jid and a private_jid if a user joins and add him as a friend with the public_jid which is transmitted via status_jid then you can wait for the reply at on_pear_info_receiver (when you call add_freind save the uuid which is returned it will be the message_id in the peer info receive) then you can pull all information from the user. thats the way how i do it. if there is a better way please let me know

**Comment by PascalVH** [comment]
I'm trying to query the user details of users that join in a group to check the age of the account.
When the on_group_status_received triggers I'll execute the following:

    if response.status.find("has joined") > 0:
        client.request_info_of_users(response.status_jid)

Then as expected, on_peer_info_received triggers but the received data is far from complete like described here.
This is the full response I receive (In response.raw_element):

`<iq id="77df3f80-56dc-48fd-9afd-315042c59f89" to="[MYBOTUSER]@talk.kik.com/CAN620XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" type="result">
    <query xmlns="kik:iq:friend">
        <item jid="[USERTHATJOINED]@talk.kik.com">
            <username>USERNAME</username>
            <display-name>DISPLAY NAME</display-name>
            <pic ts="1604828788873">http://profilepics.cf.kik.com/somehash</pic>
            <pubkey/>
        </item>
    </query>
</iq>
`

As I'm looking for the age of the account, I was expecting a value for creation_date_seconds in the response.
I Tried to friend the user first (using client.add_friend) as Basti567 suggested and then triggering client.request_info_of_users again but that makes no difference.

Or is there another/better way to get the age of an account?
Any help would be highly appreciated.
