### ISSUE TITLE
Can't start software

### ISSUE THREAD

**Issue by StarFluxGames** [tomer8007/kik-bot-api-unofficial#133]
[Log](https://imgur.com/a/TV7Twuz)

I'm trying to use the bot, and I've created a brand new test account, filled in the variables in echo_bot.py, and I'm getting this error, and it's hanging on that. Any ideas? Thanks!

**Comment by tomer8007** [comment]
Thank you for reporting this problem.
This is now [fixed](https://github.com/tomer8007/kik-bot-api-unofficial/commit/0bcc7555db3f3ce483f06f2c020e9f97ad4f17b2).

**Comment by StarFluxGames** [comment]
Awesome! Thank you. I thought I was going insane lol.
