### ISSUE TITLE
Disconnecting on Login

### ISSUE THREAD

**Issue by FrancescoMangia** [tomer8007/kik-bot-api-unofficial#134]
![immagine](https://user-images.githubusercontent.com/39461188/68071499-38f69680-fd7b-11e9-9995-2fd4037b0922.png)

Hi, 
bot is working fine on locale but having this behaviour while using SOCKSv5 proxy.
When it tries to login, it receives the first ack but it disconnects after it.

![immagine](https://user-images.githubusercontent.com/39461188/68071517-7d823200-fd7b-11e9-97d2-42e32f8f6b59.png)

**Comment by tomer8007** [comment]
Does it work fine without a SOCKS proxy?

**Comment by FrancescoMangia** [comment]
Ye it works perfectly without SOCKS, it's why I'm shaking my head

**Comment by FrancescoMangia** [comment]
Anything?

**Comment by tomer8007** [comment]
It's pretty hard for me to figure this out without having a running SOCKS proxy. Does the connection gets closed from your side or from Kik's side?
Also your SOCKS proxy is completely transperent, right? it doesn't change anything in the traffic I suppose

**Comment by FrancescoMangia** [comment]
You can use this Socksv5. 

23.8-----.14:---
**Id**: ---
**Pssw**: ----

I really dk and yeah socks is full transparent. I've tried like 9-10 SOCKSv5 providers, so it's not about the proxy.
Let me know if you get 5 minutes to give a try, thanks a lot.

**Comment by FrancescoMangia** [comment]
Let me know if anything happens

**Comment by FrancescoMangia** [comment]
Discovered that it was my bot problem and it was not about SOCKS. Thanks for patience.
