### ISSUE TITLE
Not sure where else to post this

### ISSUE THREAD

**Issue by netr** [tomer8007/kik-bot-api-unofficial#136]
Thank you for all the hard work in here. Is there any way I can get some information on how to reverse engineer myself? I can send some paypal as well. Would really love to know how you logged the packets for xmpp/ssl pinning. I can dig through the code using JEB or alternatives, but need some help on that front. Let me know. Thanks

**Comment by CheshireCaat** [comment]
You can use apps like Packet Capture (Android), or MitmProxy/SSLSplit
If you wanna reverse some cryptographic things, use Inspeckage or Frida

**Comment by tomer8007** [comment]
Basically I used `sslsplit` for MITM and reversed the Java code manually for the cryptographic stuff.
I answered similar questions before [here](https://github.com/tomer8007/kik-bot-api-unofficial/issues/5#issuecomment-342830425) and [here](https://github.com/tomer8007/kik-bot-api-unofficial/issues/22).

I hope this helps.

**Comment by netr** [comment]
Thank you so much. Sorry I didn't get back to you sooner. I will mess with SSLSplit. I've been using burp/frida for other apps to bypass header based ssl pinning.. Didn't know how to approach XMPP. That's awesome. Going to check out Inspeckage as well. Really appreciate it guys
