### ISSUE TITLE
peer_jid not accepting username.

### ISSUE THREAD

**Issue by ghost** [tomer8007/kik-bot-api-unofficial#139]
Not sure if it's just me or if it's just the client.py code but, peer_jid doesn't accept usernames, only actual jids. and within the "comments". It states:
`
:param peer_jid: The Jabber ID for which to send
 the message (looks like username_ejs@talk.kik.com)                              If you don't know the JID of someone, you can also specify a kik username here.
`
but when doing:

`peer_jid = "username"`
`message = "text"`
`self.client.send_chat_message(peer_jid, message)`

(btw "username" would be where you would input the username)
anyways it responds back with:
`
raise exceptions.KikApiException('Not a valid jid')
kik_unofficial.datatypes.exceptions.KikApiException: Not a valid jid
`

Any solutions as how i would be able to handle this?

**Comment by tomer8007** [comment]
Whoops, I'm not sure why this comment is there.
We need to call `request_info_of_username` to get the JID. I'll add it the API later today.

**Comment by tomer8007** [comment]
Fixed in [this commit](https://github.com/tomer8007/kik-bot-api-unofficial/commit/5a2c290a3c291fd72a2d90ea321dfc919ac0ee33).
