### ISSUE TITLE
How to get "captcha_result"?

### ISSUE THREAD

**Issue by tixiwi** [tomer8007/kik-bot-api-unofficial#14]
Hi. How to get "captcha_result" for sign_up?

**Comment by tomer8007** [comment]
Actually I'm not sure. I tried looking around at the captcha URL without much luck. But maybe @Jaapp- knows.

**Comment by maritaria** [comment]
The url leads to a captcha you have to solve, the result is likely posted through the Kik webkit or some other javascript callback. You cannot generate the answer using code, a human needs to do it, It's a capcha after all.

**Comment by Jaapp-** [comment]
You can see it work here: https://github.com/Jaapp-/kik-desktop/blob/master/kik_desktop/ui/register_widget.py#L92

Add "&callback_url=https://kik.com/captcha-url" to the captcha url, solve the captcha, intercept a request to something that matches "https?://kik.com/captcha-url\?response=(.*)". That's the one you need.

**Comment by tomer8007** [comment]
That's awesome.
