### ISSUE TITLE
does not work any more?

### ISSUE THREAD

**Issue by diadka** [tomer8007/kik-bot-api-unofficial#140]
OSError: Multiple exceptions: [Errno 10060] Connect call failed ('34.227.164.166', 5223), [Errno 10060] Connect call failed ('54.174.100.253', 5223), [Errno 10060] Connect call failed ('18.204.192.3', 5223)

**Comment by CheshireCaat** [comment]
I checked my account from the phone - also can't connect. This problem is on the Kik server side, it is not related to this API implementation.

**Comment by ghost** [comment]
Doesn't seem to be an issue for me.

**Comment by ghost** [comment]
@diadka Is there anything that you tried tampering with?

**Comment by diadka** [comment]
@SSHbabe sorry, dont get you..

**Comment by ghost** [comment]
@diadka you shouldn't have a hard time "getting" what I'm saying. I'm not receiving the OsError that you are receiving, so this shouldn't be a Kik server side issue.

**Comment by ghost** [comment]
A type of error like that can happen because of an os function, or a system issue(system dependant) or a threading issue or networking settings.

**Comment by ghost** [comment]
So did you try tampering with anything? What device are you trying to run the script on? Can you provide any detail?

**Comment by tomer8007** [comment]
@SSHbabe I seem to be able to authenticate successfully too.

**Comment by diadka** [comment]
it is strange that you do not have such an error. for me and another friend the connection stopped working (on the server and on the home computer). Everything worked until yesterday, but now I can’t start it.
I did: IP address replacement, used VPN of different countries

**Comment by ghost** [comment]
@diadka Anything that you were doing before it stopped working?

**Comment by diadka** [comment]
@SSHbabe Now if i use a proxy through a socket, i can start several accounts, but the connection is disconnected by the remote server and I can no longer connect to this proxy after 10 min
[WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by ghost** [comment]
The proxy is the issue.

**Comment by ghost** [comment]
Just don't use the proxy.

**Comment by diadka** [comment]
on the home computer I have a dynamic ip. After rebooting the router, the provider sends me a new ip. It doesn't help either.

**Comment by ghost** [comment]
Does the proxy still exist?

**Comment by ghost** [comment]
Maybe it's interfering with the dynamic IPs.

**Comment by diadka** [comment]
no bro. it happened both on the server and my friend at the same time

**Comment by ghost** [comment]
Well it's not occurring for me so i don't think I'll be able to solve this.

**Comment by ghost** [comment]
Have you tried re-cloning the repo?

**Comment by diadka** [comment]
@SSHbabe how this can help ? same code..and i told - it just happened yesterday in different places.

**Comment by diadka** [comment]
but I see that new accounts spam in my group

**Comment by ghost** [comment]
This entire problem is relating to your network configuration.

**Comment by ghost** [comment]
Unsolvable.

**Comment by ghost** [comment]
Well not really unsolvable but I'm not about to talk to you about your network configuration settings for hours.

**Comment by SSHbabe** [comment]
Your network is the issue.

**Comment by diadka** [comment]
i think its SSL cert block me. Cant login or create new account from 1 phone too
