### ISSUE TITLE
Bypass Captcha

### ISSUE THREAD

**Issue by angstycoder** [tomer8007/kik-bot-api-unofficial#141]
How is captcha verification done/bypassed.

Running register_client.py among other on Python 3.7

`[2019-12-26 11:08:08,803] INFO   (thread Kik Connection): [-] Register error: Captcha required
Unable to register! error information:
Captcha required`

**Comment by tomer8007** [comment]
You're [supposed to be given](https://github.com/tomer8007/kik-bot-api-unofficial/blob/312d12b73b506bc5814ee94ff3b672d4e4615c5d/kik_unofficial/datatypes/xmpp/errors.py#L31) a URL to solve the captcha by a human being. After the captcha is solved, you should follow the steps you see in [solve_captcha_wizard()](https://github.com/tomer8007/kik-bot-api-unofficial/blob/312d12b73b506bc5814ee94ff3b672d4e4615c5d/kik_unofficial/datatypes/xmpp/errors.py#L60).
