### ISSUE TITLE
Registration captcha

### ISSUE THREAD

**Issue by Siliconeduck** [tomer8007/kik-bot-api-unofficial#142]
logging in works just fine, but whenever you try to register, you get a captcha every time. i tested registering using the same kik version on a real device and i get the same issue, this doesn't happen with the latest version. i tried changing the version in the device configuration, tried changing the device, device id, android id but nothing works. what could be the issue here?

**Comment by tomer8007** [comment]
When you updated the Kik version to the latest, did you update the `classes_dex_sha1_digest` too in `device_configuratoin.py`?

**Comment by Siliconeduck** [comment]
i did. Kik servers send error code 406 "not acceptable" so i am guessing the values being sent are outdated?

**Comment by tomer8007** [comment]
You're saying that on a real mobile phone on the latest version you don't get a captcha, So if you have the time I would try to MITM and tell the difference between the real packets and the API packets.

406 "not acceptable" may mean they added a new parameter or so.

**Comment by bluemods** [comment]
It's due to your client failing the safetynet check by not responding to it before a login attempt.

This is a good thing because it at least slows down the new bot epidemic that you are likely contributing to.
