### ISSUE TITLE
How to send raw XMPP?

### ISSUE THREAD

**Issue by Dahrth** [tomer8007/kik-bot-api-unofficial#145]
How do you send xmpp? you guys have a wiki for them but how do you send them and stuff? or can't we do that?

**Comment by tomer8007** [comment]
Did you try [client._send_xmpp_element](https://github.com/tomer8007/kik-bot-api-unofficial/blob/5a2c290a3c291fd72a2d90ea321dfc919ac0ee33/kik_unofficial/client.py#L465)? You just need to subclass `XMPPElement` and implement the `serialize` method.

**Comment by Dahrth** [comment]
> Did you try [client._send_xmpp_element](https://github.com/tomer8007/kik-bot-api-unofficial/blob/5a2c290a3c291fd72a2d90ea321dfc919ac0ee33/kik_unofficial/client.py#L465)? You just need to subclass `XMPPElement` and implement the `serialize` method.

that fast also i dont really know much python and stuff could i get an example code for this?

**Comment by tomer8007** [comment]
Examples for `XMPPElement`s are all around the `datatypes/xmpp` directory, such as [this one](https://github.com/tomer8007/kik-bot-api-unofficial/blob/5a2c290a3c291fd72a2d90ea321dfc919ac0ee33/kik_unofficial/datatypes/xmpp/login.py#L16).

**Comment by Dahrth** [comment]
i see. i can add those to one of the examples right? (talking about xmpp sending)

**Comment by tomer8007** [comment]
I don't think this is something the avarage user should do unless he wants to send something that is not already implemented or tweak the internals of something.

What are you trying to do? Maybe it's worth an example or adding it to the API.

**Comment by Dahrth** [comment]
no worries. i think i understand now. i was just wondering how you guys send xmpp for sending messages and stuff

**Comment by Dahrth** [comment]
does the api do a packet sniffing/injection to send xmpp stanzas? and which function is used to send them?

**Comment by ghost** [comment]
try:

```python
from kik_unofficial.datatypes.xmpp.base_elements import XMPPElement

def _send_xmpp_element(self, message: XMPPElement):
        """
        Serializes and sends the given XMPP element to kik servers
        :param xmpp_element: The XMPP element to send
        :return: The UUID of the element that was sent
        """
xmpp_element =
"""
xmpp stanzas here
"""
#Outside scope
self.client._send_xmpp_element(xmpp_element)
return self._send_xmpp_element(xmpp_element)

**Comment by ghost** [comment]
Actually, don't try that code, give me a moment.

**Comment by Dahrth** [comment]
okay SSHbabe

**Comment by ghost** [comment]
```python
from bs4 import BeautifulSoup

from kik_unofficial.utilities.cryptographic_utilities import CryptographicUtils

class XMPPElement:
    def __init__(self):
        self.message_id = CryptographicUtils.make_kik_uuid()
        self.content_id = CryptographicUtils.make_kik_uuid() #Creating a seprate uuid for content as kik does the same.

    def serialize(self) -> bytes:
        raise NotImplementedError


class XMPPResponse:
    def __init__(self, data: BeautifulSoup):
        self.message_id = data['id']
        if data.kik:
            self.metadata = XMPPResponseMetadata(data.kik)
        self.raw_element = data


class XMPPResponseMetadata:
    def __init__(self, data: BeautifulSoup):
        self.timestamp = data['timestamp']
        self.app = data['app']
        self.qos = data['qos'] == 'true'
        self.push = data['push'] == 'true'
        self.hop = data['hop'] == 'true' if 'hop' in data.attrs else None


class Stanzas(XMPPElement):
def _send_xmpp_element(self, message: XMPPElement):
        """
        Serializes and sends the given XMPP element to kik servers
        :param xmpp_element: The XMPP element to send
        :return: The UUID of the element that was sent
        """
        while not self.connected:
            log.debug("[!] Waiting for connection.")
            time.sleep(0.1)
        if type(message.serialize()) is list:
            log.debug("[!] Sending multi packet data.")
            packets = message.serialize()
            for p in packets:
                self.loop.call_soon_threadsafe(self.connection.send_raw_data, p)
            return message.message_id
        else:
            self.loop.call_soon_threadsafe(self.connection.send_raw_data, message.serialize())
            return message.message_id

xmpp_element = """ stanzas """
Stanzas._send_xmpp_element(xmpp_element)

**Comment by ghost** [comment]
I actually hope that works because I did remove the API from my system a while ago so i'm not actually directly executing anything but rather just trying to put the pieces together and doing a few unit tests.

**Comment by ghost** [comment]
but what I could do, is provide you the source code that I wrote for my bot in the past.

**Comment by Dahrth** [comment]
i will try it out now

**Comment by ghost** [comment]
> but what I could do, is provide you the source code that I wrote for my bot in the past.

it contains:
Image sending
network mapping
blank message sending
spam
interactive PM functionality
interactive profile lookup
group joining
username logging
group leaving 
auto responding
randomize message sending
java dynamic code analysis and API hooking

**Comment by ghost** [comment]
and profile picture/name changing functionality,
IP logging.

**Comment by Dahrth** [comment]
interesting

**Comment by Dahrth** [comment]
`    Stanzas._send_xmpp_element(xmpp_element)
TypeError: _send_xmpp_element() missing 1 required positional argument: 'message'`

am i doing something wrong?

**Comment by ghost** [comment]
No, I did something wrong.

**Comment by Dahrth** [comment]
ah no worries

**Comment by ghost** [comment]
try:
```python
Stanzas._send_xmpp_element(self.message(xmpp_element))

**Comment by ghost** [comment]
AHHHHHHHHHHH

**Comment by Dahrth** [comment]
lmao what happened

**Comment by Dahrth** [comment]
now self is not defined rip weird af errors ngl

**Comment by ghost** [comment]
just annoyed at python and this API.

**Comment by ghost** [comment]
> now self is not defined rip weird af errors ngl

I'm making mistakes. he said to subclass XMPPElement but I maybe declaring the params improperly.

**Comment by Dahrth** [comment]
i see hmmm

**Comment by ghost** [comment]
I'm going to reinstall the API.

**Comment by Dahrth** [comment]
alright
