### ISSUE TITLE
Usage Help

### ISSUE THREAD

**Issue by K00lManz** [tomer8007/kik-bot-api-unofficial#146]
I'm hoping you can help me if it isn't too much. I'm learning python and would like a project to learn from. I'm having trouble connecting to the kik servers. How? & What all do I need to download in order to do so? Hoping you can help, once i'm logged in I can start practicing and changing things up from there i'd think.

**Comment by tomer8007** [comment]
I think the example on the main page pretty much explains itself, if you have more specific questions/error messages you may ask them.
