### ISSUE TITLE
How to I recive and read message

### ISSUE THREAD

**Issue by ghost** [tomer8007/kik-bot-api-unofficial#147]
I have went throu ```class KikClient``` and only found functions for sending messages is there I way to get message that was sended to me

**Comment by tomer8007** [comment]
Fetching chat history is not supported right now.
The best you can do is to fetch roster (list of chat partners) and try to implement fetching history using [the protocol described in the wiki](https://github.com/tomer8007/kik-bot-api-unofficial/wiki/Message-Formats#history-retrieval).
