### ISSUE TITLE
Message Timestamp

### ISSUE THREAD

**Issue by Madrid-Lux** [tomer8007/kik-bot-api-unofficial#149]
Hey, is there a way to send a message with a specific timestamp?
Some bots do it & I'm not sure how it would work?

**Comment by tomer8007** [comment]
I think it could be done by editing the timestamp in [this line](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/xmpp/chatting.py#L30).

**Comment by Madrid-Lux** [comment]
Thanks, I'll try that.
