### ISSUE TITLE
Can't get chat partners

### ISSUE THREAD

**Issue by Mickyfubu** [tomer8007/kik-bot-api-unofficial#15]
when I try to `get_chat_partners` I am almost always met with the error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 16383: unexpected end of data` or `AttributeError: 'NoneType' object has no attribute 'children'
`

**Comment by maritaria** [comment]
It may be that your account receives a list that the api is incapable of parsing for some reason. I would be interrested in having a copy of the raw result if possible.

**Comment by Mickyfubu** [comment]
id be more than happy to provide a copy if only I could get the method to work. I'll keep trying and if it finally works I will send one.

**Comment by tomer8007** [comment]
That's not the lastest version from GitHub.

The line `if user.a or user["a"]` was changed to `if user.a or "a" in user` in [this commit](https://github.com/tomer8007/kik-bot-api-unofficial/commit/593128aad7da1f2e414467d1445888b3a11ac090). I believe this should fix the problem.

**Comment by Mickyfubu** [comment]
Thank you so much that worked great

**Comment by Mickyfubu** [comment]
I am now having a recurring error message

`  File "/home/micky/Documents/kik desktop/Inactives bot 2/kikclient.py", line 199, in get_chat_partners
    chat_partners = list(map(self._parse_chat_partner, list(response.query.children)))
  File "/home/micky/Documents/kik desktop/Inactives bot 2/kikclient.py", line 710, in _parse_chat_partner
    return KikClient._parse_user_jid_element(element)
  File "/home/micky/Documents/kik desktop/Inactives bot 2/kikclient.py", line 720, in _parse_user_jid_element
    jid_info["display_name"] = element.find('display-name').text
AttributeError: 'NoneType' object has no attribute 'text'
`

**Comment by tomer8007** [comment]
That's because the API assumes there exists a 'display-name' property in every user JID element. What functions did you use to get this error?

**Comment by Mickyfubu** [comment]
get_chat_partners

**Comment by tomer8007** [comment]
I added checks for these fields, please try again from the GitHub version
