### ISSUE TITLE
Admin status for on_group_message_received?

### ISSUE THREAD

**Issue by Madrid-Lux** [tomer8007/kik-bot-api-unofficial#151]
Hey, sorry I'm kinda bombarding the issues these couple of days lol, I know I'm only supposed to do issue by issue, but this is not really a bug, just can't seem to figure it out.
I've been playing around a lot & I really can't seem how to see a member's admin status with `on_group_message_received`.
Does anyone have any examples? Thanks in advance. :)

**Comment by tomer8007** [comment]
Do you mean a group admin?

If you are an admin, maybe you can try to `promote_to_admin`/`demote_admin` a member and see if you get a different status.

And why is `on_group_message_received` related? is there a system message that's getting sent whenever someone becomes an admin?

**Comment by Madrid-Lux** [comment]
I mean just checking if the member sending the message in `on_group_message_received` is admin in that group or not.

**Comment by tomer8007** [comment]
You should be able to request information about the group with `request_roster`, and once you get an `Group` object, you can iterate its memebers and check the [ is_admin field](https://github.com/tomer8007/kik-bot-api-unofficial/blob/5a2c290a3c291fd72a2d90ea321dfc919ac0ee33/kik_unofficial/datatypes/peers.py#L81).
