### ISSUE TITLE
Listing group members

### ISSUE THREAD

**Issue by bobbyJame** [tomer8007/kik-bot-api-unofficial#162]
This isn't really an issue but I am wondering if you know of a way to list members of a group and check admin statuses of members, I've looked at some of the closed issues and don't seem to be getting anywhere.

If you have an example for listing group members or checking member admin status, it would be greatly appreciated.

**Comment by tomer8007** [comment]
If the group is in your roster, I think the list of members should be there. You can see all the information in the [Group](https://github.com/tomer8007/kik-bot-api-unofficial/blob/1e1dbcdbf0184d072f13911cbf704d38bf2505eb/kik_unofficial/datatypes/peers.py#L55) object.
Try something like:
``` python 
def on_roster_received(self, response: FetchRosterResponse):
        for peer in response.peers:
            if isinstance(peer, Group):
                group_members = peer.members
```

You can also you the `is_admin` property.

**Comment by bobbyJame** [comment]
ON ifinstance(peer, Group)
I get error 'Group' is not defined

**Comment by bobbyJame** [comment]
With is_admin I just receive 'User' object has no attribute 'is_admin'.

I need to check if the member sending the message is admin.

**Comment by bobbyJame** [comment]
So I have managed to get it to print out the members and whether they're admin but it looks like this:
<kik_unofficial.datatypes.peers.GroupMember object at 0x7fac8841c460> is admin

my code:
for peer in response.peers:
			if str(peer).startswith("Group("):
				for member in peer.members:
					print(member)
					if member.is_admin == True:
						print(member, "is admin")

**Comment by tomer8007** [comment]
What's the problem with that? You seem successful

**Comment by bobbyJame** [comment]
How can I retrieve the jid of the member instead of <kik_unofficial.datatypes.peers.GroupMember object at 0x7fac8841c460>

**Comment by bobbyJame** [comment]
It is only showing object locations when I iterate through the members field

**Comment by tomer8007** [comment]
`member.jid`

**Comment by bobbyJame** [comment]
Ok got it now. Thank you very much.
