### ISSUE TITLE
Bot stops listening to events after a while

### ISSUE THREAD

**Issue by learningpythons** [tomer8007/kik-bot-api-unofficial#163]
Hello, it was already discussed on another thread (https://github.com/tomer8007/kik-bot-api-unofficial/issues/71) that the bot will hang when internet disconnects, i think i can solve this by myself. What is happening to me is that even if internet is on, the bot stop listening to events after a while (let's say 5 minutes). So if i send a message from another account to the bot account it won't be logged by the bot. How can I solve this?

**Comment by tomer8007** [comment]
You need to understand why the bot stops listening for events. Try to enable `DEBUG` logs if you haven't already done so and see if there any connection related logs.

**Comment by learningpythons** [comment]
I turned on the debugger but there is no output.

**Comment by Doktor-Apokalypse** [comment]
Every 2 minutes I call...

self.client.send_stanza("< ping / >")

(no spaces between quotes) 
...and now doesn't disconnect even if no communication with bot in gc or dm

**Comment by TriSerpent** [comment]
> Every 2 minutes I call...
> 
> self.client.send_stanza("< ping / >")
> 
> (no spaces between quotes) ...and now doesn't disconnect even if no communication with bot in gc or dm

Send_stanza is just for auth, it doesn't take args like that. Also the function is in auth_stanza not client anyways. 
There's your issue i guess, [ping it with a callback instead.](https://github.com/tomer8007/kik-bot-api-unofficial/discussions/211#discussioncomment-2010704)

**Comment by Doktor-Apokalypse** [comment]
> Every 2 minutes I call...
>
> self.client.send_stanza("< ping / >")
>
> (no spaces between quotes) ...and now doesn't disconnect even if no
> communication with bot in gc or dm
>
> Send_stanza is just for auth, it doesn't take args like that. Also the
> function is in auth_stanza not client anyways.
> There's your issue i guess, ping it with a callback instead.
> <https://github.com/tomer8007/kik-bot-api-unofficial/discussions/211#discussioncomment-2010704>
>

Sorry, forgot to show code. This is off the top of my head, I'll edit if
it's wrong when I get back to my computer.


​from​ ​kik_unofficial​.​datatypes​.​xmpp​.​base_elements​ ​import​
​XMPPElement​

    def send_stanza(self, stanza: XMPPElement)
        # Returns UUID of sent XMPP
        XMPP_data = bytes(stanza, "utf-8")
        if type(XMPP_data is list:
            for item in XMPP_data:
                self.loop.call_soon_threadsafe(
self.connection.send_raw_data, item)
            return item.message_id
        else:
                self.loop.call_soon_threadsafe(
 self.connection.send_raw_data, XMPP_data
        return XMPP_data.message_id

>

**Comment by Doktor-Apokalypse** [comment]
Modified my client.py


def send_stanza(self, XMPP_msg)
	stanza = XMPP_msg.encode()

	self.loop.call_soon_threadsafe(
self.connection.send_raw_data,
stanza)



Know it def works because when set logging.DEBUG can see the pong response from kik to every ping i send

**Comment by tomer8007** [comment]
Closing this in favor of #71 .
