### ISSUE TITLE
Trouble sending messages

### ISSUE THREAD

**Issue by sapiosaurus** [tomer8007/kik-bot-api-unofficial#164]
Is anyone having difficulty sending group messages using the library? The debug log shows the message going out, as well as a read/delivered receipt. Some are occasionally accepted, but typically only after the initial connection. Sending more than a few events seems to null route the messages/receipts being sent to the Kik API.

**Comment by bluemods** [comment]
Is it still occurring? @drmarvel Wouldn't surprise me if it was a Kik server issue.
