### ISSUE TITLE
Adding people to a group

### ISSUE THREAD

**Issue by Madrid-Lux** [tomer8007/kik-bot-api-unofficial#165]
Is there any way to add people into a group, knowing they're in the friends list?
I have looked at the code & didn't really see it mentioned anywhere.

**Comment by bluemods** [comment]
```<iq type="set" id="[Crypto UUID]">```
    ```<query xmlns="kik:groups:admin">```
	```<g jid="[Group JID]">```
	    ```<m>[USER_JID]@talk.kik.com</m>```
	```</g>```
    ```</query>```
```</iq>```

**Comment by Madrid-Lux** [comment]
How is that used?
Is there a function, & what's Crypto UUID?

**Comment by tomer8007** [comment]
You're looking for [add_peer_to_group](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L284):
```
client.add_peer_to_group(group_jid, peer_jid)
```

**Comment by Madrid-Lux** [comment]
Exactly what I was looking for; thank you so much!
