### ISSUE TITLE
Classes and callbacks

### ISSUE THREAD

**Issue by Jaapp-** [tomer8007/kik-bot-api-unofficial#17]
There's a couple of issues with the current codebase. First of all some methods are long and messy. It would be nice to do a major refactor. Let's gather some ideas.

- Use classes for users, groups, messages. Peer (with jid) is extended by User and Group, Group is extended by PublicGroup and PrivateGroup.
- Instead of the user having to figure out the type of the next message, let the user extend a KikClient and implement callback functions for the ones they're going to use. E.g. for a simple bot this would result in something like this:
```python
class MyKikBot(KikClient):
    def on_group_message(self, group_message: GroupMessage):
        group.send(GroupMessage("You sent: {}".format(group_message.message)))
```
- The current API can't send and receive messages simultaneously because they both "claim" the socket. The way around this is to keep track of message ids, do sending and receiving asynchronously, this would go along nicely with previous point.

Maybe I could make a basic version of this. Anyway, we can use this thread for future plans.

**Comment by tomer8007** [comment]
Absolutely has to be done. 

Unfortunately I am not sure I could work on this in the next few days but a basic version of this as you said will be great.

**Comment by tomer8007** [comment]
Wow, the work you've done on your fork is fantastic. Please let me know when it's ready.
