### ISSUE TITLE
Module not found Xiphias

### ISSUE THREAD

**Issue by Jumvah** [tomer8007/kik-bot-api-unofficial#175]
I have got a basic bot running under PyDroid3 on my android phone using Kik-Unofficial, transferred everything over to Python3 on Win10 and get this error:

Traceback (most recent call last):
  File "D:\Python\proteus4_build24.py", line 32, in <module>
    from kik_unofficial.datatypes.xmpp.xiphias import *
ModuleNotFoundError: No module named 'kik_unofficial.datatypes.xmpp.xiphias'

I have installed every module that I had running under PyDroid and still get this message.

My brain is melting as I have been at this for 4 hours now, installing every module dependency that I can. I am new to Python and I am really not understanding why it can't find the module.

**Comment by tomer8007** [comment]
Can you post a reproducible example for Windows?

**Comment by Jumvah** [comment]
![140f672d-8940-422c-bc6e-6560c37d8268](https://user-images.githubusercontent.com/47386553/101633750-a1548480-3a1f-11eb-8d72-42745e995155.jpg)

first run couldn't do colorama. installed that fine, but second run gave xiphias error. i have uninstalled and reinstalled (git, pycharm, python 3.9 and kik-bot-api-unofficial) and still no joy.

**Comment by bluemods** [comment]
Use python 3.7.x instead of 3.9.x.

3.9 seems to have a lot of issues when running the client

**Comment by tomer8007** [comment]
I can successfully do `from kik_unofficial.datatypes.xmpp.xiphias import *` on Windows 10 and Python 3.9, so to further debug this we'll need full code.

**Comment by Jumvah** [comment]
I fixed it by moving from Python 3.9 to 3.8
wont be moving back up to 3.9 till I know glitches are fixed.
