### ISSUE TITLE
unable to get creation date from xiphias_get_users_by_alias in a public group

### ISSUE THREAD

**Issue by QTpyeRose** [tomer8007/kik-bot-api-unofficial#178]
in `xiphias.py` under `class UsersResponseUser:` in the descriptive comment of what the function does it states
```
    Alias jids provided in public groups (used with client.xiphias_get_users_by_alias):
        Includes all the private profile data (username, display_name, etc) of a user
        if you're chatting with them, else it'll get the local jid -->and the creation date.<--
```
but when `client.xiphias_get_users_by_alias(chat_message.alias_sender).creation_date_nanos` is called it throws the error `'str' object has no attribute 'creation_date_nanos'`, so it appears to not have been created. either a piece of code is missing or the comment describing what it does is wrong (or i messed up my code in some way)

**Comment by tomer8007** [comment]
Take a look at [this example](https://github.com/tomer8007/kik-bot-api-unofficial/issues/174#issuecomment-737492359), I think it has what you want,

**Comment by bluemods** [comment]
Some Kik accounts are known to be glitched and not have the account creation time in the xiphias response. It's unknown why this happens, but it only typically happens for older accounts. An example on Kik would be @CinnamonHollow

**Comment by QTpyeRose** [comment]
my code was actually wrong. I was forgetting to get the user object out the array it provided (I thought it was just a direct user responce)
