### ISSUE TITLE
is there some sort of discord or social media group?

### ISSUE THREAD

**Issue by QTpyeRose** [tomer8007/kik-bot-api-unofficial#179]
I know this is a bit off-topic for issues, but it would be very helpful if there was a group where people who use this program could congregate and help each other if one does not already exist

**Comment by tomer8007** [comment]
I can think of two ways:
1. The public group in Kik messanger itself, see issue #117 
2. The [Discussions](https://github.com/tomer8007/kik-bot-api-unofficial/discussions) in this repository

**Comment by QTpyeRose** [comment]
thank you, I joined the public group
