### ISSUE TITLE
this is a bad idea

### ISSUE THREAD

**Issue by Mickyfubu** [tomer8007/kik-bot-api-unofficial#18]
I think having this publicly available was a cool idea to start but clearly needs to stop. Every account that's ever been logged into your client is getting deleted and the client is just going to get patched and end up getting other clients patched and essentially ruining the fun of the development community on Kik. Plus it's practically a trap now since anyone logging into it gets banned.

**Comment by tomer8007** [comment]
Are you seriously saying that Kik is deleting every account that uses this? Will that happen immediately in the first time? Because I did not see it.

Also, if they just detect it based on a certain condition (say, constant device ID) it is trivial to fix it.

**Comment by maritaria** [comment]
Note that changing the deviceID will probably mean you have to solve a new captcha

**Comment by tomer8007** [comment]
I mean, maybe what triggers the ban is, for example, logging in to too many accounts from the same device. In these kinds of cases, we can just let the user start with a different one.

**Comment by maritaria** [comment]
From the protobuf files I've found that CAN means an android device, you can use CIP for iphone. Also the string after CAN is not self-validating so just use any similar string

**Comment by maritaria** [comment]
>  Every account that's ever been logged into your client is getting deleted

Any proof? My bot and real account are fine...
What kind of activity have you been doing?

**Comment by maritaria** [comment]
Alright so one of my bots has been banned, will try with new device ID

**Comment by Mickyfubu** [comment]
Most of my bots didn't even send any data to like it only collected data from groups for analysis. Some accounts had only been logged into the client one time. But still got banned. 

22 of my accounts got banned and only 3 of them had been logged into more than a few times.

Also an extra note is have you considered the amount of power this could give to someone with poor intentions... Of this became popular it could result very poorly for Kik and for the users. Anyone could do pretty malicious things that only a few could do before. Those few who were able went through the trouble and work to learn it and they don't abuse it. Just a thought maybe you should consider what you're actually giving people access too I've already seen it being abused a bit

**Comment by Mickyfubu** [comment]
I've run more than 100 accounts from actual Kik apks and never had an issue. And none of the accounts I run like that ever got banned...

**Comment by tomer8007** [comment]
Did you register the bots using the API or with the apk?

**Comment by Mickyfubu** [comment]
I registered with the app a long time ago. They were all accounts I made legit and they had never done anything to raise any flags. They never even got a complicated captcha before and now they are super ultra mega banned

**Comment by tomer8007** [comment]
Okay, we have to find the reason for this. Is sending a message with the API is enough to get banned immediately?

**Comment by Mickyfubu** [comment]
Do you have a Kik where we could talk and I could show you exactly what I'm talking about ?

**Comment by tomer8007** [comment]
Not really, sorry.

**Comment by Mickyfubu** [comment]
No one's being banned immediately it's happening in waves. Every so often every account that as used with the client is being banned. Not just me either, other people I know that used it have been banned too. It's very unforgiving.

**Comment by tomer8007** [comment]
I think it depends on how you use it, because the one or two bots I created were not banned.

If I were kik I would block accounts based on suspicous activity like the ones I mentioned. After all, the network packets that the apk and the API send out should be somewhat identical. At least at the protocol level.

**Comment by Mickyfubu** [comment]
Every account I logged into got banned. Even accounts that literally never sent any data to Kik aside from the login. Accounts that only were logged into once got banned. It's beyond suspicious activity. I'm not the only one who had this issue either. I had even some bots running from a different IP and friends of mine had the same issues without doing anything out of the ordinary. The only commonality is the API

**Comment by tomer8007** [comment]
Alright. How can I tell if I got banned? Does the login should fail? Did you try changing the device ID/android ID? One possible cause I could think of is that too accounts were created with the same parameters.

**Comment by Mickyfubu** [comment]
If you got banned then your account won't be able to be logged into, and you won't be able to chat with it. If you send a message it'll still be in new chats.

**Comment by tomer8007** [comment]
I am able to log in through the API so I guess it's not banned.

Did you try changing the hardcoded parameters (like `android_id`)?

**Comment by Mickyfubu** [comment]
I haven't made any changes since all the bans. Last night all the accounts I used were banned same with many others. I know how to prevent the future bans, I just wanted to let you know that I, and the majority of the Kik development and modding community, thinks you should take this down.

**Comment by tomer8007** [comment]
How it's possible to prevent future bans?

I don't think this client is going to get "patched" specifically by kik because it's not popular. plus, much larger projects like [Yowsup](https://github.com/tgalal/yowsup) don't really seem to get into a cat-and-mouse game.

I'm not sure I understand. Do you already know what exactly makes kik ban those users?

**Comment by Mickyfubu** [comment]
I don't know exactly what makes them banned but I definitely have some decent anti-ban strategies I'll put in place

**Comment by tomer8007** [comment]
If we can prevent the ban why won't we do it then

**Comment by Mickyfubu** [comment]
Because the ban isn't what the concern is. The concern is what some people can and will do with the client.

**Comment by tomer8007** [comment]
This is a much more general trust problem. People made unofficial APIs for other apps like WhatsApp, Snapchat, Facebook and much more. 

Of course people can make nasty things, but they can also make cool things.

**Comment by Mickyfubu** [comment]
Yeah there will be some cool things... But I don't think the trade off is equal. Every time someone makes a custom client not another app it comes with so many issues. This would easily make the sex bot issues so much worse. Besides I think the people that would make the cool stuff are already doing so I'm the APK and would be capable of making a client.

**Comment by Mickyfubu** [comment]
My Kik is @micky.apk could you please message me and I could show you what I'm talking about.

**Comment by maritaria** [comment]
There are some things the lib doesn't implement, like answering certain challenges

**Comment by Mickyfubu** [comment]
What do you mean

**Comment by maritaria** [comment]
Especially on newer versions kik servers sends a challenge to the client that it has to solve. For example a captcha but also some hashing algorithms that are done by the code in the background.

**Comment by Jaapp-** [comment]
Banning unwanted accounts is the responsibility of Kik servers, not ours. This is a neutral API. If someone makes sex bots, let Kik servers ban them. If I make a desktop client, let people enjoy that.

If you want to discuss on Kik: I recently made the #kikbotapi public group for discussion of this project, feel free to join. (Maybe include a link in README?)

**Comment by Jaapp-** [comment]
> There are some things the lib doesn't implement, like answering certain challenges
There won't be a captcha breaking algorithm but forwarding captcha's to the user is pretty trivial and already done for registering accounts.

**Comment by connorbode** [comment]
Don't listen to him, this is a great idea.

**Comment by mzstalker** [comment]
Eve Assistant and Adam Bot have thousands of users. We get banned here and there, but its nothing. This is what everyone uses to make a Python Bot. Keep up the great project!

**Comment by tomer8007** [comment]
Closing this issue because I don't think this project is a bad idea.
