### ISSUE TITLE
interactive client simultaneously reading and writing

### ISSUE THREAD

**Issue by QTpyeRose** [tomer8007/kik-bot-api-unofficial#180]
the interactive client simultaneously reads and writes, while typing a message if you are delivered a message it will interrupt your typing and truncate the message you send. see image below
![Capture](https://user-images.githubusercontent.com/65490493/103533145-d2bb4700-4e49-11eb-885d-769af5b7bbb3.JPG)

in this case, only "orld" would be sent by the bot

I know the message format looks a little different, I'm using photon_clinet.py (the client I'm designing) from my personal fork. but this also happens with the default interactive_client.py, I came across it cause I'm trying to fix it in mine and posted this cause I don't know how to solve it.

**Comment by tomer8007** [comment]
Yes, basically what we want is to read input from the user and print in the same time (from two different thread), something similar to [this StackOverflow question](https://stackoverflow.com/questions/54299399/print-and-input-at-the-same-time-python-multithread).

**Comment by Sitiaro** [comment]
(For dms)

a = input('Enter your message: ')
 self.client.send_chat_message(chat_message.from_jid, a)

It'll prompt an input statement in the terminal and you'll be able to reply back to the user's message. You can do that for groups as well.

![kik1](https://user-images.githubusercontent.com/46511306/115121748-fc454c00-9fbc-11eb-8f21-73ea7766b642.PNG)
![kik2](https://user-images.githubusercontent.com/46511306/115121750-fea7a600-9fbc-11eb-977c-022c812cefd6.PNG)
![kik3](https://user-images.githubusercontent.com/46511306/115121751-00716980-9fbd-11eb-8ba5-179dad77b313.PNG)
