### ISSUE TITLE
Is it possible to resolve an ajid?

### ISSUE THREAD

**Issue by Sitiaro** [tomer8007/kik-bot-api-unofficial#190]
I've been trying to add a feature to grab the username of the person joining a chat but all I'm able to grab is the ajid. Is there a way to resolve ajid's that can help me with this? Or maybe some other method?

**Comment by tomer8007** [comment]
What's an `ajid`? You can grab the username of a `jid`, not sure if you already know that or if it helps

**Comment by Sitiaro** [comment]
An alias jid? (Example - m0q4h1l91g12bny1vmjleh788mmm7z7dje4uvt6mto0s16tuwj50_a@talk.​kik.​com)
Can you show me an example of how to grab username of a jid when someone joins?

**Comment by tomer8007** [comment]
You can try to use the `request_info_of_users` function with your `jid` or `ajid`:
https://github.com/tomer8007/kik-bot-api-unofficial/blob/d64551195c5afb5b03c854a5e7f84a77c98fe06c/kik_unofficial/client.py#L234

In case that won't work, it's probably also worth trying to replace  `jid=` with `ajid=` in this line:
https://github.com/tomer8007/kik-bot-api-unofficial/blob/d64551195c5afb5b03c854a5e7f84a77c98fe06c/kik_unofficial/datatypes/xmpp/roster.py#L70

**Comment by Sitiaro** [comment]
Got it, thank you.
