### ISSUE TITLE
Invite links

### ISSUE THREAD

**Issue by Jumvah** [tomer8007/kik-bot-api-unofficial#194]
Is it possible to generate an invite link like:

kik.me/g/dXUK7LRw2NbNs5FTGESAxCVCJo3

As I wish to send it via self.client.send_link( ) as looks better than #grouphash posted in gc when I have done it manually. But don't know how the code is generated. 

![IMG_20210524_030256](https://user-images.githubusercontent.com/47386553/119286583-9cd20000-bc3c-11eb-87d2-40d913918afe.jpg)

**Comment by tomer8007** [comment]
This feature does not exist in the API right now.
