### ISSUE TITLE
Video sending?

### ISSUE THREAD

**Issue by Lettuce8373** [tomer8007/kik-bot-api-unofficial#195]
I notice that there was no feature for sending videos. I can receive videos and such, and I can send images with send_chat_image but there is no send_chat_video. Is there code for this that I can add anywhere to the API? I am aware that the API currently doesn't have such a feature. Is there no available code for this? Any plans of implementing this?

**Comment by tomer8007** [comment]
I don't plan to implement this and I don't know about such code.
If you want, you can you can try to [capture kik traffic](https://github.com/tomer8007/kik-bot-api-unofficial/issues/5) yourself and figure out the code. Also maybe @bluemods can help.

Related issues: #171 and #189.

**Comment by Lettuce8373** [comment]
I believe BlueMods has left kik.

**Comment by ghost** [comment]
Kik is dead losers, go to telegram or discord

**Comment by GreenBed** [comment]
Lettuce8373:
BlueMods hasn't left Kik, he just keeps getting hunted/banned there, so he is mainly on Telegram for now. (@BlueIsLeet)

Ancurserv:
Of course it is, but some still enjoy the communities there. If you aren't interested in Kik anymore, you should really find something better to do with your time than commenting on issues for a Kik bot.

**Comment by oztats** [comment]
> Lettuce8373:
> BlueMods hasn't left Kik, he just keeps getting hunted/banned there, so he is mainly on Telegram for now. (@BlueIsLeet)
> 
> Ancurserv:
> Of course it is, but some still enjoy the communities there. If you aren't interested in Kik anymore, you should really find something better to do with your time than commenting on issues for a Kik bot.

Idk... That cool kid said we're losers... If Blue died for our sins then I better get Telegram right away!
