### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by TriSerpent** [tomer8007/kik-bot-api-unofficial#201]
Does anyone know how to resolve this error?

ImportError: cannot import name 'PeersInfoResponse' from 'kik_unofficial.datatypes.xmpp.roster' (/opt/virtualenvs/python3/lib/python3.8/site-packages/kik_unofficial/datatypes/xmpp/roster.py)

**Comment by tomer8007** [comment]
@TriSerpent Still having this error?
