### ISSUE TITLE
Can't install dependencies when using python 3.8

### ISSUE THREAD

**Issue by enigmatic21** [tomer8007/kik-bot-api-unofficial#202]
I'm able to run it perfectly on kali but termux gives me this error when I try installing the dependencies using python 3.8. 

ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-req-build-9x0rztxc/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-req-build-9x0rztxc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-m1jybzvs
         cwd: /data/data/com.termux/files/usr/tmp/pip-req-build-9x0rztxc/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/dist.py", line 38, in <module>
        from setuptools import windows_support
      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen failed: cannot locate symbol "ffi_closure_free" referenced by "/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_ctypes.cpython-38.so"...
    ----------------------------------------
WARNING: Discarding file:///data/data/com.termux/files/home/kik-bot-api-unofficial. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I tried doing it on termux on an android emulator too and it gave me the same error.

**Comment by tomer8007** [comment]
@enigmatic21 Is this still happening for you? Some Termux-related problems were solved.

**Comment by tomer8007** [comment]
Closing because this seems to be resolved.
