### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by TriSerpent** [tomer8007/kik-bot-api-unofficial#203]
I'm getting the error:
AttributeError: type object 'KikClient' has no attribute 'log_format'

coming from this:
`        def main():
            logger = logging.getLogger()
            logger.setLevel(logging.INFO)
            stream_handler = logging.StreamHandler(sys.stdout)
            stream_handler.setFormatter(logging.Formatter(KikClient.log_format()))
            logger.addHandler(stream_handler)`
and this:
`        if __name__ == '__main__':
            main()
            logging.basicConfig(format=KikClient.log_format(), level=logging.INFO)`

when I'm just running the echobot example with no modifications.
Does anyone know how to resolve this?

**Comment by tomer8007** [comment]
Pretty obvious, but `log_format` does exist, so try to debug that further.
https://github.com/tomer8007/kik-bot-api-unofficial/blob/1237897aca896175a51c5ff7aba6a24d4a429d19/kik_unofficial/client.py#L692

**Comment by ilike3pancakes** [comment]
@tomer8007 #238 removed log_format

https://github.com/tomer8007/kik-bot-api-unofficial/pull/238/files#diff-8989ede1fdedd4f6e27b2752cd58ef2355307273f037a9d7324a334b5a6c8309L12

But it still appears in examples

https://github.com/search?q=repo%3Atomer8007%2Fkik-bot-api-unofficial%20log_format&type=code
