### ISSUE TITLE
Offline messages

### ISSUE THREAD

**Issue by r0bman** [tomer8007/kik-bot-api-unofficial#205]
Is there a way to get messages sent whilst the bot is disconnected?
The kik app receives offline messages when signed in again.

**Comment by tomer8007** [comment]
Did you try retrieving history?

**Comment by r0bman** [comment]
I mean people who sent a first message, what would show as chat requests in the app.

**Comment by BaconPeeks** [comment]
> I mean people who sent a first message, what would show as chat requests in the app.

Yeah, as tomer said you'd need to request history for these messages to show up when you login again. The api won't request history be default.

**Comment by tomer8007** [comment]
You can request history using the `request_messaging_history` method, this is probably tha API you're looking for:
https://github.com/tomer8007/kik-bot-api-unofficial/blob/1cc91cf3c83df247bd41908a7f4461e711744385/kik_unofficial/client.py#L390
