### ISSUE TITLE
Why can't I change the version number?

### ISSUE THREAD

**Issue by gituserdxd** [tomer8007/kik-bot-api-unofficial#21]
I want to change the version number in case kik decides to ban all bots running on that version like they did before few weeks ago but every time I change it I either get a captcha or it stops working all of the sudden (yes I know how to generate a hash for the right version but that didn't help either I tried to change it to 11.36.0.18816 with this classes.dex hash 2UIy3Mfb27X3WOC9tGSR7W7uBwU= and its result was  7Wf/GLP3AX8UKDjL29jsxwp071A= ). Any idea how can I fix this problem?

**Comment by tomer8007** [comment]
What about 'apk_signature_hex'? Did you change that too?

**Comment by gituserdxd** [comment]
@tomer8007 No I thought signature stays same for all versions? Isn't that how kik is able to install updates over old versions?

**Comment by tomer8007** [comment]
Oh right.
So supposing you changed the references to the version number in all places, It might be that Kik changed something in newer versions that is not implemented yet in the API.

But Is it possible that the version change actually did work, and you are getting banned because of another reason?

**Comment by gituserdxd** [comment]
@tomer8007 I did change references in all the places and after changing my device ID I didn't get a captcha anymore but for some reason it still always shuts down few seconds after establishing the session for some reason. You think it could have something to do with your hard coded values like install date and the number of logins?

**Comment by tomer8007** [comment]
Yes, that could be the case. Did you try changing them too? Also, do you get an error if you set an invalid version?

**Comment by tomer8007** [comment]
@gituserdxd The version number was upgraded to 13.4.0.9614. Please tell me if it's working for you now.

**Comment by gituserdxd** [comment]
@tomer8007 alright I will check when I have my PC with me. Btw you might wanna change the host name to talk1340an.kik.com for this version

**Comment by tomer8007** [comment]
Why? Is it faster?

**Comment by gituserdxd** [comment]
@tomer8007 I just think it will be better because it will make you seem less sketchy to kik and blend in with others who are using that version. Being on version 13 and connecting to version 11 server could make you stand out and be an easy target for ban

**Comment by gituserdxd** [comment]
btw @tomer8007 im able to login fine now using normal login method instead of node on latest version. but now i get this stanza sent to me whenever I log in. Idk if this is something  should be worried about but have a look

<.message xmlns="jabber:client" id="95d4fdb6-7378-41a8-9a32-8beb94830171" from="webpushbot_xyz@talk.kik.com" type="chat" to="topniglet_y1g@talk.kik.com"><.kik push="false" qos="false" hop="true" timestamp="1529869837438" app="all"/><.request xmlns="kik:message:receipt" d="false" r="false"/><.xiphias-mobileremote-call method="TriggerSafetyNetCheck" service="mobileremote.antispam.safetynet.v1.MobileSafetyNet"><.body/><./xiphias-mobileremote-call><./message>

**Comment by gituserdxd** [comment]
btw @tomer8007 im able to login fine now using normal login method instead of node on latest version. but now i get this stanza sent to me whenever I log in. Idk if this is something  should be worried about but have a look

<.message xmlns="jabber:client" id="95d4fdb6-7378-41a8-9a32-8beb94830171" from="webpushbot_xyz@talk.kik.com" type="chat" to="(my jid)"><.kik push="false" qos="false" hop="true" timestamp="1529869837438" app="all"/><.request xmlns="kik:message:receipt" d="false" r="false"/><.xiphias-mobileremote-call method="TriggerSafetyNetCheck" service="mobileremote.antispam.safetynet.v1.MobileSafetyNet"><.body/><./xiphias-mobileremote-call><./message>

**Comment by tomer8007** [comment]
Yes, I saw it too. I don't know if it's something to worry about. I think that for now it is prefered over having to log in with a kik node.

I will try changing the server address soon.

**Comment by gituserdxd** [comment]
Alright btw do you have telegram? I made an app for kik that I think you might find useful when updating version numbers

**Comment by tomer8007** [comment]
**Update**
Changing the kik version is now easier as it's possible to add it in the `device_configuration.py` file.
