### ISSUE TITLE
Get username or jid from a group message containing alias jid

### ISSUE THREAD

**Issue by AriDeve** [tomer8007/kik-bot-api-unofficial#214]
Heya, I was wondering how one would get an username or a normal jid from a message sent in a group, so the user could be added as a friend.

Adding friends doesn't seem to work with alias jid, and I cannot seem to get a normal jid as no matter what method I use to try to convert either username or jid is not present.

**Comment by BaconPeeks** [comment]
No, There is not: This is the point of the alias jid to encrypt the user's username.

**Comment by AriDeve** [comment]
But then, how does kik itself add friends?

**Comment by BaconPeeks** [comment]
you know how you search someone's username then send them a message?

Kik sends a friend attribution request upon sending that first message, The receiver sends one when they reply. Thus how people get added to your contacts.

**Comment by AriDeve** [comment]
That pretty much explains it, thank you. Will re-open if I run into issues with that, but probably won't need to,
