### ISSUE TITLE
client.register method

### ISSUE THREAD

**Issue by BaconPeeks** [tomer8007/kik-bot-api-unofficial#219]
I am trying to create a program to help making accounts be easier, but for some reason whenever i call the register it does nothing??

**Comment by BaconPeeks** [comment]
The method never actually executes so my script sits waiting and i eventually get '</stream:stream' from the server killing the connection

**Comment by Mac0r0ni** [comment]
its ded

**Comment by tomer8007** [comment]
@BaconPeeks I suspect your 'does nothing' has something to do with 657ac09c9a7b34e488acda28efa5c89a35ae50e4. Please try it now and re-open if needed.
