### ISSUE TITLE
**** API FAILS LOGIN AFTER CAPTCHA ****

### ISSUE THREAD

**Issue by Doktor-Apokalypse** [tomer8007/kik-bot-api-unofficial#223]
Kik have done something that has completely broken this API. All bots now go to captcha and then wont log-in after throwing an error:
`AttributeError: 'My_Project_Bot' has no attribute 'login'`

Is this API still being maintained? Or is there a newer python API that can do everything this one does?

Only just got my head around python and this API, and the moment my admin bot becomes capable enough to release into the wild, Kik fcks around and destroys 2 years of my work.

I'm far too old to be learning a new language just to use a different API

If anybody can help....Thanks

**Comment by Dyingatm** [comment]
I tried updating device_configuration.py:
kik_version_15_49_info = {'kik_version': '15.49.0.27501', 'classes_dex_sha1_digest': '5o61frOsakJJ2iCYafCoKHtyu7w='}

kik_version_info = kik_version_15_49_info        # a kik version that's not updated might cause a captcha on login

but didnt work..

maybe @bluemods can help you, He is the only one still working on it I think.

**Comment by Doktor-Apokalypse** [comment]
I tried the kik version from my burner phone and generated the SHA1 digest:
`kik_version_15_49_info = {'kik_version': '15.31.0.23938', 'classes_dex_sha1_digest': 'iJ7HR5j5VbMGCkiRJYZ4AvvsGTg='}`
and used the android and device ID from that phone, and that helped nothing either.

**Comment by Dyingatm** [comment]
Here is some info regarding the SHA1 digest which doesnt make any sense due to a unlogical pattern :

kik_version_11_info = {"kik_version": "11.1.1.12218", "classes_dex_sha1_digest": "aCDhFLsmALSyhwi007tvowZkUd0="}
 #found in Manifest and Cert

kik_version_13_info = {"kik_version": "13.4.0.9614", "classes_dex_sha1_digest": "ETo70PFW30/jeFMKKY+CNanX2Fg="} 
#found in version 14.0.0.11130 & 13.4.0.9614 in Manifest

kik_version_14_info = {"kik_version": "14.0.0.11130",  "classes_dex_sha1_digest": "9nPRnohIOTbby7wU1+IVDqDmQiQ="}
 #not found at all neither in cert or manifest

kik_version_14_5_info = {"kik_version": "14.5.0.13136", "classes_dex_sha1_digest": "LuYEjtvBu4mG2kBBG0wA3Ki1PSE="} 
 #found in Manifest

kik_version_15_21_info = {'kik_version': '15.21.0.22201', 'classes_dex_sha1_digest': 'MbZ+Zbjaz5uFXKFDM88CwFh7DAg='} #found in Cert

Your version doesnt seem to exist on the NET, I was only able to find 15.31.1.23601.

**Comment by BlareNation** [comment]
> 

How do I get ahold of @bluemods? If anyone can solve this new issue with kik, ill pay them 1K.

**Comment by bluemods** [comment]
> > 
> 
> How do I get ahold of @bluemods? If anyone can solve this new issue with kik, ill pay them 1K.

You must be involved in a lot of spam bot activity if you are willing to pay that much for a fix.

Edit: after my reply, he deleted the post and changed his username: https://api.github.com/user/108567187
Be careful what information you put out in public, spammers are watching and waiting for help, as you can see.

**Comment by Doktor-Apokalypse** [comment]
That was my first thought as soon as I saw that reply. He's probably part
of the reason it's been patched.

**Comment by BL4RE** [comment]
If you think 1k is a lot of money you should re-evaluate your life. Just saying...

I also think you are confused on where you think you are.. this is github not dontsharehub. You're on here policing these threads commanding people not to share information. What kinda authority do you think you have here? You wouldn't be as far as you are with Kik, if you didn't read the information shared here, you moron.

**Comment by Doktor-Apokalypse** [comment]
1k is a lot of money when on disability

**Comment by himbeermuffin** [comment]
In the last time the API has been used for too many bad things and Kik has become a place where hobby devs with entirely peaceful intentions aren't right anymore. 
I’ve been watching more and more malicious code has being shared publicly. Therefore, Kik's reaction was to be expected. 
I think it's time to focus on new projects (: tty on tg.

**Comment by JustNiceGuy** [comment]
They did a bad job at "patching" it, just saying. I mean what else can we expect from them.

**Comment by tomer8007** [comment]
It appears you can still try to login without Captcha for some users, for example
```
Username: a
Password: b
[2023-03-21 00:04:29,848] INFO   (thread Kik Connection): [+] Initiating the Kik Connection thread and connecting to kik server...
[2023-03-21 00:04:30,747] INFO   (thread Kik Connection): [!] Connected.
[2023-03-21 00:04:31,126] INFO   (thread Thread-1 (_on_new_data_received)): [+] Logging in with username 'a' and a given password *...
[2023-03-21 00:04:31,765] INFO   (thread Thread-3 (_on_new_data_received)): [-] Login error: Password mismatch
```

@Doktor-Apokalypse @bluemods 
Anyway, 75471620fdbb93061a11c1b31366479509b25022 created some problems so I committed 657ac09c9a7b34e488acda28efa5c89a35ae50e4. Now, you can solve the CAPTCHA using a browser and the API works nicely:
```
[2023-03-21 00:01:53,551] INFO   (thread Thread-3  ): [-] Login error: a Captcha is required to continue
To continue, complete the captcha in this URL using a browser: https://captcha.kik.com/?id=3-CAISoQFrYysZg8XXEtOCv46jpdyGUAK.....
Next, intercept the request starting with 'https://kik.com/captcha-url' using F12, and paste the response parameter here: eyJraWQi.......m5Q
[2023-03-21 00:03:57,414] INFO   (thread Thread-3  ): [+] Logging in with username 'XXXXXXX' and a given password ******...
[2023-03-21 00:03:59,044] INFO   (thread Thread-5  ): [+] Logged in as XXXXXXX
Full name: XXXXX XXXXXXXX
[2023-03-21 00:03:59,044] INFO   (thread Thread-5  ): [+] Closing current connection and creating a new authenticated one.
[2023-03-21 00:03:59,044] INFO   (thread Thread-5  ): [!] Disconnecting.
[2023-03-21 00:04:00,045] INFO   (thread Kik Connection): [+] Initiating the Kik Connection thread and connecting to kik server...
[2023-03-21 00:04:00,974] INFO   (thread Kik Connection): [!] Connected.
[2023-03-21 00:04:00,974] INFO   (thread Kik Connection): [+] Establishing authenticated connection using kik node 'XXXXXXX_v2y'...
[2023-03-21 00:04:01,679] INFO   (thread Thread-7  ): [+] Authenticated successfully.
```

**Comment by bluemods** [comment]
Usernames are 2 characters minimum though, so I'm not sure the first example is valid. I appreciate you checking it out though. I will probably adapt this into my repo and submit a PR back soon

**Comment by tomer8007** [comment]
@bluemods Oh, yeah, this is a better explanation, so you can forget about my first claim.

**Comment by Doktor-Apokalypse** [comment]
thanks guys. this helped a lot. got connection now. still locks up after
solving captcha, but just restarting the script logs me in fine now.

**Comment by tomer8007** [comment]
@Doktor-Apokalypse Can I close this issue?

**Comment by vipguy** [comment]
Captcha is still needing to be solved , I'd say not fixed 👍

**Comment by tomer8007** [comment]
OK. Adding #37 and #59 for reference.

**Comment by tomer8007** [comment]
Closing this issue because the reported error does not happen anymore and the captcha is understandable,
