### ISSUE TITLE
on_login_ended is seemingly never called

### ISSUE THREAD

**Issue by ilike3pancakes** [tomer8007/kik-bot-api-unofficial#229]
This makes it hard to get self JID

I suspect there's been some change in the response xml on login so that this doesn't work anymore:

https://github.com/tomer8007/kik-bot-api-unofficial/blob/a8657f212d3cca6ce646911825829177532d7687/kik_unofficial/xmlns_handlers.py#L160

Would you take a PR aiming to simply add some diags/debug logs here?

**Comment by tomer8007** [comment]
If all you want to do is to figure out why `on_login_ended` never gets called, why wouldn't you debug it locally?

**Comment by ilike3pancakes** [comment]
I don't actually need it

If you're not interested feel free to close

**Comment by tomer8007** [comment]
If it never gets called it is a bug, though.

**Comment by TheGreatCodeholio** [comment]
`on_login_ended` only gets called if logging in with username/password. If you are logging in using a kik_node and authenticated session it will not get called, on_authenticated gets called.
