### ISSUE TITLE
Sending images

### ISSUE THREAD

**Issue by quantum2111** [tomer8007/kik-bot-api-unofficial#23]
Hi! Thank you for great API. Do you plan to add sending multimedia?
Maybe somebody have a function for sending images?

**Comment by tomer8007** [comment]
My first priority currently is adding a function for joining a group.
But depending on how complex this will be I might add sending multimedia too in this opportunity.

Sorry for not having much time to add features anyway.

**Comment by tomer8007** [comment]
For visitors from the future: This is now [merged](https://github.com/tomer8007/kik-bot-api-unofficial/pull/124/files).
