### ISSUE TITLE
Could someone do a small tutorial

### ISSUE THREAD

**Issue by steveboy199** [tomer8007/kik-bot-api-unofficial#231]
Sending users mesages through sms is a little pricey so we decided to go through the free version  using kik. They however stooped their developer portal and thus we are here. I just messed around with the create credntials, and the examples. However I cant seem to get anything working. I have received the 406 error code and a ssl handshake error. I was able to run and create a credentials file although.

**Comment by tomer8007** [comment]
Maybe you could paste the erros you are getting
