### ISSUE TITLE
Group information

### ISSUE THREAD

**Issue by ucantaffordwifi** [tomer8007/kik-bot-api-unofficial#234]
Is it possible to find a group's info (JID and/or Hashtag/Code) with just the link of the group's PFP?

Example:
**URL**: https://profilepics.cf.kik.com/OCh9T-ZfUfCg_i7x-MvAZI0vKk8/thumb.jpg?ts=1695173759496
**Code**: #roleplayersunited1
**JID:** 1100233373249_g

Trying to find the group info from this URL: https://profilepics.cf.kik.com/kZhwdtjtNO40jPtrAEdJj0hiDKA/thumb.jpg?ts=1695174442573

**Comment by tomer8007** [comment]
I don't think this is possible.

**Comment by bluemods** [comment]
URL: http://profilepics.cf.kik.com/kZhwdtjtNO40jPtrAEdJj0hiDKA/thumb.jpg
Code: #pokemonrp163
JID: 1100261395846_g

You're welcome

**Comment by tomer8007** [comment]
@bluemods How did you do that?
