### ISSUE TITLE
Get messages by username

### ISSUE THREAD

**Issue by diashkhan** [tomer8007/kik-bot-api-unofficial#24]
is there anyway to collect all the messages i had with a person by that persons username. i am new to python. Thanks in advance.

**Comment by diashkhan** [comment]
is there anyway to collect all the messages i had with a person by that persons username. i am new to python. Thanks in advance.

**Comment by tomer8007** [comment]
I don't think so, not currently in the API at least.

Depending on how complex this will be I might implement it in the future.

**Comment by diashkhan** [comment]
No other way to collect messages?

**Comment by diashkhan** [comment]
or is there any way to get unread message id and partner username?

**Comment by tomer8007** [comment]
You can get the partners list by using the roster function.

**Comment by tomer8007** [comment]
Okay, I see the [Message Formats](https://github.com/tomer8007/kik-bot-api-unofficial/wiki/Message-Formats) wiki page actually does have message formats for retrieving history.

**Comment by diashkhan** [comment]
i am new to this and i don't understand that language :/

**Comment by xorist** [comment]
It's not difficult (now in the future, at least) to parse out and save messages that you receive and send, then save them wherever you like.
