### ISSUE TITLE
hello i want to talk with you 

### ISSUE THREAD

**Issue by stefannn11** [tomer8007/kik-bot-api-unofficial#247]
hello i want to talk with you where can we talk because i need help on that bot

**Comment by vipguy** [comment]
This is not an issue

**Comment by tomer8007** [comment]
@stefannn11 If you just need help running the bot you can open a discussion in the discussions tab. I'd prefer that over one-on-one guidance.

**Comment by stefannn11** [comment]
hey bro i want a kik bot that joins on a livestream then it text all
viewers of that live like a spam bot
