### ISSUE TITLE
Sending read receipts on groups

### ISSUE THREAD

**Issue by rodsan0** [tomer8007/kik-bot-api-unofficial#25]
As far as I understand it, send_read_confirmation() only allows sending read receipts to PMs. I tried to implement it, but the official API is not help either (https://dev.kik.com/#/docs/messaging#receipts) with the only example being sending a receipt to a PM.

**Comment by tomer8007** [comment]
Will try to look into this when I'll have the time..
What you can do in the meantime is looking at the Message Formats wiki page and sending various XML requests in a logical syntax. Maybe it'll work.

**Comment by hunterbeach** [comment]
Any update on this? Having the same issue here.

**Comment by tomer8007** [comment]
Thanks for remainding this.
I just sniffed a bit to see how it looks like and basically the read receipt is sent to the person that sent the message, even inside a group.
I added an extra `g` tag in the relevant XMPP to make sure it's sending the same XML as the app.
@rodsan0 @theman00011 Please tell me if you can now send read receipts for groups in the `new` branch.

**Comment by hunterbeach** [comment]
@tomer8007 It doesn't seem to be working for me. I get the message in console that it is sending the read receipt to my JID for the message ID but the message doesn't appear as read on my device. Here is the data that chatting.py is producing.

`` <message type="receipt" id="e482ad50-8b47-417e-a8d2-91d1db6c5e02" to=[My JID] cts="1528958370566"><kik push="false" qos="true" timestamp="1528958370566" /><receipt xmlns="kik:message:receipt" type="read"><msgid id="2e6dbd7d-5027-42b7-a026-62300188f44f" /></receipt><g jid=[group JID] />``

Something else I noticed, sending the read receipt to a group seems to break after one try. I do a command to send a receipt once and the bot replies and it says it sent it. I try it again and the bot never replies until I restart the script. If I remove the ``+ group_line if group_line is not None else '' +`` from chatting.py it doesn't freeze up. If I add it again, it freezes after the first receipt again.

**Comment by hunterbeach** [comment]
I seemed to have fixed both issues by changing the OutGoingReadReceipt class in chatting.py to

```python
class OutgoingReadReceipt(XMPPElement):

    def serialize(self):
        timestamp = str(int(round(time.time() * 1000)))
        group_line = "<g jid=\"{}\" />".format(self.group_jid)
        data = ('<message type="receipt" id="{}" to="{}" cts="{}">'
                '<kik push="false" qos="true" timestamp="{}" />'
                '<receipt xmlns="kik:message:receipt" type="read">'
                '<msgid id="{}" />'
                '</receipt>').format(self.message_id, self.peer_jid, timestamp, timestamp, self.receipt_message_id)
        if 'groups' in group_line:
            data = data + group_line + '</message>'
        else:
            data = data + '</message>'
        return data.encode()
```

There is probably a better way to do it but I am not super good at Python yet. But changing

``+ group_line if group_line is not None else '' +``

to 

``+ group_line if 'groups' in group_line else '' +``

Didn't seem to work for some reason but the way I did it above did. So let me know if you want to do it a different way or if you would like me to submit a pull request to change it.

**Comment by tomer8007** [comment]
Yeah, I really wasn't completely sure this line will work. Apparently some python thing.

Please submit a pull request.
