### ISSUE TITLE
Error when using fresh account because of missing key

### ISSUE THREAD

**Issue by petrekova** [tomer8007/kik-bot-api-unofficial#29]
When creating a fresh account and not having any chats, you can't call any methods without running into errors.

For example, executing the example code from the `README.MD` results in following error:
```python
 File "test.py", line 4, in <module>
    kik.send_message("other_kik_username", "Hello from bot!")
  File "/some/path/kik_unofficial/kikclient.py", line 365, in send_message
    jid = username if groupchat else self._resolve_username(username)
  File "/some/path/kik-bot-api-unofficial/kik_unofficial/kikclient.py", line 801, in _resolve_username
    raise Exception("Failed to convert username to kik node")
```
 This is because in [kikclient.py](https://github.com/tomer8007/kik-bot-api-unofficial/blob/master/kik_unofficial/kikclient.py) on line 789 function `_resolve_username` expects `self.user_info` to have the key `chat_list` (which a fresh account of course doesn't have).

This can be easily fixed by putting a check beforehand, such as
```python
 if self.user_info is not None:
            if "chat_list" in self.user_info: # -> fix
                for node in self.user_info["chat_list"]:
                    if node[:node.rfind('_')] == username:
                        return node + jid_domain
```

**Comment by tomer8007** [comment]
Nice, thanks for the report.
This is now fixed.
