### ISSUE TITLE
Can my bot be banned because of hard coded timestamp?

### ISSUE THREAD

**Issue by schmidhuber** [tomer8007/kik-bot-api-unofficial#35]
I see that timestamp(ts) is hard coded https://github.com/tomer8007/kik-bot-api-unofficial/blob/master/kik_unofficial/kikclient.py#L152 Why is it so? When I use current unix timestamp, my bot fails.
```
Traceback (most recent call last):
  File "examples/send_message.py", line 30, in <module>
    main()
  File "examples/send_message.py", line 12, in main
    chat_partners = kik_client.get_chat_partners()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kik_unofficial/kikclient.py", line 196, in get_chat_partners
    self._make_request(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kik_unofficial/kikclient.py", line 666, in _make_request
    response = self._get_response()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kik_unofficial/kikclient.py", line 672, in _get_response
    raise KikEmptyResponseException(response, "Kik server returned empty response")
kik_unofficial.kik_exceptions.KikEmptyResponseException: Kik server returned empty response
```
Can my bot be banned because of I don't change my timestamp?

**Comment by tomer8007** [comment]
I think it's more likely your bot was banned because of a hardcoded device/Android ID.
There is a current pull request that addresses that. Did you check it out?
Also, what happens if you change the timestamp? Do you get un-banned?

**Comment by schmidhuber** [comment]
I didn't get banned yet :) I just assumed that my bot could be banned because of the hard coded "timestamp". I use different "devise id" and "android id" in my requests. But when I change "timestamp", I get the error that I described before:  "Kik server returned empty response". If I use the hardcoded "timestamp", everything is okay. That's weird.

**Comment by tomer8007** [comment]
Hmm.
This is weird indeed. I think I already encountered this issue somewhere on the past but I don't wuite remember what was the cause (If i found it). Maybe I could investigate this again soon.

Did you try seeing if there are any other hardcoded stuff sent to kik server? Did you try timestamps that are close to this one?
My best guess would be it's something about signatures.

**Comment by schmidhuber** [comment]
I remember how I faced that error. I was able to reproduce it a few times. First time when I log in (with not hard coded timestamp), everything goes smoothly. (device id and android id are not from this repo, I generated my own). But, the second time when I log in (timestamp is not hard coded again), I get that error. This is very odd. One more thing that I think could cause this error is that I created kik account using my phone, instead of using this API. I'm gonna investigate this. For now I'm using timestamp from my first login(it's not from this repo, it's my own). That first login was successful, and every time I use timestamp from that login, everything goes well. (I use that timestamp only for login, I don't use it for messages and other stuff).

**Comment by tomer8007** [comment]
@gituserdxd I was asked this question before, and actually I don't know myself.
It just so happened that at some point I noticed that if I change the timestamp to anythign else (except one milisecond above what it is right now), kik servers reset the connection.
I am convinced there is a reason for this, but finding it will require more investigation.

**Comment by tomer8007** [comment]
**Update**
~~@gituserdxd has uploaded the java code for generating the timestamp, kik-style. Translation to python is needed.
https://github.com/gituserdxd/KikCustomTimeStuff~~

@CheshireCaat has [implemented it](https://github.com/tomer8007/kik-bot-api-unofficial/pull/123/files).
