### ISSUE TITLE
Include __init__ file in protobuf folder

### ISSUE THREAD

**Issue by motatoes** [tomer8007/kik-bot-api-unofficial#39]
Hi!

I was getting the following error after installing it locally

    kikclient.py", line 16, in <module>
        from kik_unofficial.protobuf import group_search_service_pb2
    ModuleNotFoundError: No module named 'kik_unofficial.protobuf'

I fixed it by creating a file `__init__.py` in the protobuf folder

**Comment by tomer8007** [comment]
Fixed.
