### ISSUE TITLE
Can't auth 2 or more accounts

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#42]
Hi, I use my own library, which I wrote on the basis of those found on the github
The principle of work is the same, but I have a problem

When I authorize only 1 account - everything is fine

if I try to authorize 2 or more in a row there are errors
[R]error code="406" 
type="modify"
not-acceptable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"
password-mismatch xmlns="kik:error"
/error
[R] k ok="0"  badhost k

But password is correct!
I know that the library is different, but what could be the reason?

**Comment by tomer8007** [comment]
Maybe that's because it's the same connection

**Comment by CheshireCaat** [comment]
If I show the C # code, can you help?

I was thinking about using 1 connection,
but in essence, for each thread must create its own connection and write/read streams

How can I find out more precisely? Is it possible?

**Comment by CheshireCaat** [comment]
I found the answer, thx)

**Comment by CheshireCaat** [comment]
I find the answer

I try to create different accounts in one variable

When i create a list of accounts it works correctly in multi-threading
