### ISSUE TITLE
Receiving images

### ISSUE THREAD

**Issue by hunterbeach** [tomer8007/kik-bot-api-unofficial#46]
I have made a handler for receiving image messages in one-on-one chats that I plan on making a pull request for, but I can't seem to figure out group picture messages. When receiving a group picture message, nothing happens, not even raising a NotImplementedError. Does anybody have any ideas why this could be or has a capture of a group picture message?

**Comment by tomer8007** [comment]
Do you see nothing in `_on_new_data_received` when you receive a group picture message?
Maybe post the handler code so I can understand it better.

**Comment by hunterbeach** [comment]
I think I figured out the problem. When it receives a PM with a image, it doesn't hit any of the clauses in the MessageHandler class so it raises a NotImplementedError so I made another clause and handler for the image message to check if it is an image, and to handle it if so.

```python
def handle(self, data: BeautifulSoup):
        if data['type'] == 'chat':
            if data.body:
                self.callback.on_chat_message_received(IncomingChatMessage(data))
            elif data.find('friend-attribution'):
                self.callback.on_friend_attribution(IncomingFriendAttribution(data))
            elif data.find('status'):
                self.callback.on_status_message(IncomingStatusResponse(data))
            elif data.find('images'):
                self.callback.on_image_received(IncomingImageMessage(data))
            else:
                raise NotImplementedError
```



But, in group messages, it triggers the 
```python
elif data.content and 'app-id' in data.content.attrs:
            app_id = data.content['app-id']
            if app_id == 'com.kik.ext.stickers':
                self.callback.on_group_sticker(IncomingGroupSticker(data))
```

clause in the GroupMessageHandler class so it checks app_id which is ``com.kik.ext.gallery`` so it doesn't raise an error but it doesn't complete because it's not a sticker. So this brings the question, should image messages get passed to IncomingChatMessage and IncomingGroupChatMessage and get handled separately there or should they get passed to their own IncomingImageMessage class where they get their own callback? I think it's own handler class and callback would be better since if I change the group content clause to 

```python
elif data.content and 'app-id' in data.content.attrs:
            app_id = data.content['app-id']
            if app_id == 'com.kik.ext.stickers':
                self.callback.on_group_sticker(IncomingGroupSticker(data))
            elif app_id == 'com.kik.ext.gallery':
                self.callback.on_image_received(IncomingImageMessage(data))
            elif app_id == 'com.kik.ext.camera':
                self.callback.on_image_received(IncomingImageMessage(data))
```

It receives and passes images in groups to it's handler perfectly to my IncomingImageMessage class and callback.

**Comment by tomer8007** [comment]
Hmm, I think maybe we should union `IncomingChatMessage` and `IncomingGroupChatMessage` as well as `OutgoingChatMessage` and `OutgoingGroupChatMessage` in the future because eventually it will have more similarities.

Additionally, I think that maybe from the programmer's point of view it'll be more comfortable to receive all incoming messages (group, chat, images...) in one callback like `on_chat_message_received` and filter it then based on maybe an additional `type` field in `IncomingChatMessage`. That's because they're all chat messages.

Actually I'm not sure. What do you think? 
If it's working right now when it's saparated then you may submit the pull request.

**Comment by hunterbeach** [comment]
If it wouldn't take too much work, then consolidating all the chat messages into one callback seems like the best plan. It would probably have to have two fields, one for the type of message (Text, image, sticker, etc.) and one for the type of chat (PM or group). That would probably help with supporting formats in both groups and PM's because at the moment for example, I don't think stickers are supported in PM's.

I'll go ahead and start trying to consolidating them together. I don't think it should be too hard since most messages share a lot of similarities.

**Comment by tomer8007** [comment]
That's really great, thanks
Does it all work for you now with an additional `IncomingImageMessage` class?

**Comment by hunterbeach** [comment]
Yeah, with the additional IncomingImageMessage class it works great on both camera and gallery pictures. It is just a small change from the others, here's what it looks like.

```python
class IncomingImageMessage(XMPPResponse):
    def __init__(self, data: BeautifulSoup):
        super().__init__(data)
        self.request_delivered_receipt = data.request['d'] == 'true'
        self.requets_read_receipt = data.request['r'] == 'true'
        self.image_url = data.find('file-url').get_text()
        self.status = data.status.text if data.status else None
        self.from_jid = data['from']
        self.to_jid = data['to']
```

**Comment by tomer8007** [comment]
Looking good.
Want to submit a pull request for now?

**Comment by hunterbeach** [comment]
Sure, I'll submit it for now and hopefully soon I will have them all moved into one class and callback. I didn't include any of the other image data in the class like the image hashes, or the base64 encoded image preview because I doubt anybody would want a lower quality picture but it could be easily added by someone if they wanted to get the picture without making another web request to get the original picture or something.

**Comment by tomer8007** [comment]
Cool

**Comment by hunterbeach** [comment]
It should be good to go now, maybe double check that you're able to receive images with the new callback. I added an example in the Echo_bot.py, everything looked good in the pull request but I was having Git issues with my local directory being out of sync but I think all my changes got put back in after resyncing but you might just double check to make sure it's all working.

**Comment by tomer8007** [comment]
Yes, I can see the latest changes there too.

**Comment by hunterbeach** [comment]
Great, I'll see if I can start consolidating the classes and callbacks now.
