### ISSUE TITLE
Not really an issue but a pull request.

### ISSUE THREAD

**Issue by SamHoque** [tomer8007/kik-bot-api-unofficial#47]
```
<iq type="set" id="[GUID]">
    <query xmlns="kik:groups:admin">
	<g jid="[GUID]">
	    <n>[GROUPNAME]</n>
	</g>
    </query>
</iq>
```
This will change the group name of the groups if you are an admin

Had to work on XMPP's for my project so thought I would post it here so other people can get help from it :)

**Comment by tomer8007** [comment]
That's cool.
Is it working for kik?

**Comment by SamHoque** [comment]
Yes, it is working. I have tested it.

**Comment by SamHoque** [comment]
You can also do 
```
<iq type="set" id="[GUID]">
    <query xmlns="kik:groups:admin">
	<g jid="[GUID]">
	    <m>[USER_JID]@talk.kik.com</m>
	    <m>[USER_JID]@talk.kik.com</m>
	    <m>[USER_JID]@talk.kik.com</m>
	</g>
    </query>
</iq>
```

to add multiple users to a group chat.

**Comment by tomer8007** [comment]
Useful.
Want to submit a pull request?

**Comment by SamHoque** [comment]
I don't really use github so I don't know how. You could add it to the wiki That's why I posted it here.

**Comment by tomer8007** [comment]
Thanks, I added it to the wiki.

**Comment by SamHoque** [comment]
Could you also update the version number? I will post another comment in a bit. Gonna log the classes_dex sha-1.

**Comment by tomer8007** [comment]
I'm afraid this is going to break some stuff.
Maybe you should first test it to make sure it's working.

**Comment by SamHoque** [comment]
Version: 13.4.0.9614

Classes.dex: ETo70PFW30/jeFMKKY+CNanX2Fg=

Base64 Hmac: VQUwYTyS9uWy6u0oGqVskoFY1cM=

**Comment by SamHoque** [comment]
I just replace the return String of kik/android.c,smali method d with `VQUwYTyS9uWy6u0oGqVskoFY1cM=` and everything works fine. I mostly mod kik.

**Comment by tomer8007** [comment]
Did you test it?
What about the APK signature?

**Comment by SamHoque** [comment]
APK Signature always stays the name as far as I know? I do not have python installed on my pc. You could test it, It will take 2 minutes. but I tested it with the raw kik apk by replacing the return string with the base64 Hmac ID.

**Comment by tomer8007** [comment]
Oh, right, the "signature" of APKs is actually the certificate used to sign it. Correct?

**Comment by SamHoque** [comment]
as far as in android terms in the signature class it always stays the same. `Signature[] sigs = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_SIGNATURES).signatures;` this will always stay the same. if it changes they wont be able to update the kik app over the older kik app from play store.

**Comment by tomer8007** [comment]
Yeah, cause it returns the certificate.
Also if you unzip it and do `keytool -printcert -file ANDROID_.RSA` you can get the SHA1 fingerprint of the same thing.

**Comment by SamHoque** [comment]
I did it in another way. I wrote my self a jar that prints out any kik version info, I just drag and drop.

**Comment by tomer8007** [comment]
@LynxKik How do you modify the kik APK to see traffic? Do you use Frida? or do you manually edit the smali files and reinstall? which methods?

**Comment by SamHoque** [comment]
I manually edit the smali file. I have been modding kik for 3 years now. I have know smali as much as I know java. It's kik/android/net/b for outgoing and kik/android/net/a for incoming. (the classes)

**Comment by tomer8007** [comment]
That's very nice.
How did you find these classes?

**Comment by SamHoque** [comment]
I have made bots, auto reply and auto type for kik. I started grepping where kik handles their output and input stream.

**Comment by SamHoque** [comment]
Do you have discord? if so add me, I don't think talking in the comments is a good idea SamzSakerz#4758

**Comment by tomer8007** [comment]
No sorry
I will try to test the new version you posted.

**Comment by tomer8007** [comment]
It works, but I now receive a new `message` when I log in:

`<message xmlns="jabber:client" to="[KIK_NODE]@talk.kik.com" from="webpushbot_xyz@talk.kik.com" type="chat" id="723b1fc0-f7da-4a2f-93bb-3cb2e0761436"><kik hop="true" app="all" timestamp="1529080644972" qos="false" push="false"/><request r="false" d="false" xmlns="kik:message:receipt"/><xiphias-mobileremote-call method="TriggerSafetyNetCheck" service="mobileremote.antispam.safetynet.v1.MobileSafetyNet"><body/></xiphias-mobileremote-call></message>`

Do we need to somehow satisfy the SafetyNet check? Does it prevent the client form doing anything?

**Comment by SamHoque** [comment]
Hmm, I am not really sure I don't really mod kik 13.4, I don't go above kik 10.17 because of the new style changes kik made. I don't think it will effect anything. and staying on the latest versions of kik will reduce the chance of getting captcha in login/register. `<xiphias-mobileremote-call method="TriggerSafetyNetCheck" service="mobileremote.antispam.safetynet.v1.MobileSafetyNet"><body/></xiphias-mobileremote-call>` never seen this before.

**Comment by tomer8007** [comment]
Yes, I think it's worth it. I commited that.
