### ISSUE TITLE
Find group

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#48]
Hi, is it possible to find group by keyword?
For example "games" and get the list as:
 - games + group_id
 - gamesgroup + group_id
etc
I did not find this information on the wiki
I'm trying to intercept traffic through a fiddler, but I can not yet

**Comment by SamHoque** [comment]
Looks like an easy task to do, I will try to get the traffic if I have extra time.

**Comment by CheshireCaat** [comment]
LynxKik, hello
How do you intercept traffic?

**Comment by tomer8007** [comment]
@CheshireCaat  Did you see `on_group_search_response(self, response: GroupSearchResponse)`?
If I remember correctly you're supposed to get the list in this callback after calling `search_group`.

Also to capture traffic manually from the kik app see [this issue](https://github.com/tomer8007/kik-bot-api-unofficial/issues/5).

**Comment by SamHoque** [comment]
I do not intercept the traffic, I mod the kik apk and print out the traffic in text files.

**Comment by SamHoque** [comment]
I logged the stanza but it's weird. I never seen anything like this so far. https://hastebin.com/hoduvonuxe.bash you can have a look at it. I uploaded it to hastebin. It's the response I believe.

**Comment by SamHoque** [comment]
I think this will get the popular groups response, I am not sure. 

Haven't worked with group searches yet.

`<iq type="get" id="9c6a8a55-b706-42b8-8a8f-df8faced58a1"><query p="8" ts="1529073934500" xmlns="jabber:iq:roster" /></iq>`

**Comment by SamHoque** [comment]
Okay, After decoding the base64 with a base64 decoder that hastebin just sends response of suggested groups.

**Comment by SamHoque** [comment]
I figured it out. this is what you sent out ```<iq type="set" id="440d07bd-8789-4e37-9962-0c88e3126840"><query xmlns="kik:iq:xiphias:bridge" service="mobile.groups.v1.GroupSearch" method="FindGroups"><body>CgF0</body></query></iq>``` CgF0 is a base64 string it is decoded to `t` then it will send a response like above I put in hastebin!

**Comment by CheshireCaat** [comment]
@LynxKik thanks you! Great!

**Comment by tomer8007** [comment]
@CheshireCaat @LynxKik  This is all [already implemented](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/xmpp/roster.py#L107).

**Comment by CheshireCaat** [comment]
I apologize, did not look into the code
Excellent! Thank you for your help

**Comment by SamHoque** [comment]
That's great then
