### ISSUE TITLE
Getting 406 error while logging in

### ISSUE THREAD

**Issue by madlabman** [tomer8007/kik-bot-api-unofficial#49]
Hi! I received 406 error after login attempt. Any idea?

[-] Kik error code: 406
Traceback (most recent call last):
`<error code="406" type="modify">`
  File "/kik-bot-api-unofficial/examples/send_message.py", line 29, in <module>
 `<not-acceptable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>`
    main()
`</error>`

**Comment by tomer8007** [comment]
Umm what?
Could you post the log when you set the logging level to DEBUG?
Also you should use the `new` branch, not `master`. It's much more supported.

**Comment by madlabman** [comment]
Thanks a lot! With `new` branch it works.
