### ISSUE TITLE
Password mismatch

### ISSUE THREAD

**Issue by madlabman** [tomer8007/kik-bot-api-unofficial#50]
Every time I try to sign in get this error. username/password pair is correct, of course.
`[2018-06-16 16:18:56,880] INFO   (thread Kik Connection): [-] Login error: Password mismatch`

**Comment by tomer8007** [comment]
It works for me, I'm not sure what are you trying to do

Are you trying to authenticate more than one account in a row?

**Comment by madlabman** [comment]
I'm trying to run `interactive_client.py` inside `examples` package with `username` and `password` variables set to actual values.

**Comment by tomer8007** [comment]
I just tried it, it works. Does it work for you in the `echo_bot.py` example?

**Comment by madlabman** [comment]
Nope, it also returns `Login error: Password mismatch`

I clone `new` branch and run `pip3` installer provided by your readme file instruction.
I use Python 3.6.5 on MacOS.

What other information do you need for debug this case?

**Comment by tomer8007** [comment]
If you set the username to `your_kik_username`, you get `Unregistered` error, right?
Also did you test it with other accounts?

Maybe post the DEBUG log.

**Comment by madlabman** [comment]
As you mentioned after setting username to `your_kik_username` I have `Login error: Not Found (Not Registered)`.

I tried to login via all known accounts and by newly registered account too.

[Debug log (I replace username with 'my-username')](https://github.com/tomer8007/kik-bot-api-unofficial/files/2108148/kik-debug.log)

**Comment by tomer8007** [comment]
Hmm.
Did it work for you previously? My best bet would be it's becuase the kik APK version was upgraded in the latest commits. Try to see if it's working [with these changes undone](https://github.com/tomer8007/kik-bot-api-unofficial/commit/330c84545bf5938aaeaa1b3265519da32528be58).

**Comment by madlabman** [comment]
It's my first try with your project, so it didn't work for me.
At older commit before apk version changed it doesn't work for me too.

**Comment by tomer8007** [comment]
So when you said it works with the `new` branch what happened?
Also can you sign up using the API?
Another guess - try to change the Android ID/Device ID

**Comment by madlabman** [comment]
After changing Android ID/Device ID it works fine.
