### ISSUE TITLE
What is the group_search_service_pb2.py?

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#52]
Hi, i working only on C# and i don't quite understand what this file is for

I thought that the methods of obtaining and processing results after searching for groups
At the same time, I ran into a problem - I was able to repeat the request for a C # group search, but I can not figure out how to get a response
Does this mean that I need to transfer the code from this file to C #?

**Comment by tomer8007** [comment]
This file is an auto-generated file that represents kik's response for group searches.
It was generated by Google's [Protobuf](https://developers.google.com/protocol-buffers/) compiler - protoc. You can download it from the official page and make a C# version of it.

**Comment by CheshireCaat** [comment]
@tomer8007 can you show/send me source (group_search_service.proto)?

**Comment by tomer8007** [comment]
[group_search_service.zip](https://github.com/tomer8007/kik-bot-api-unofficial/files/2109254/group_search_service.zip)

**Comment by CheshireCaat** [comment]
Thanks you! You can close this issue)
