### ISSUE TITLE
Can't generate own proto

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#53]
Hello!
I asked about the group_search_service.

I tried to compile the file that you dropped me, but found errors
Where to get the missing links?)
Error photo: 
![image](https://user-images.githubusercontent.com/30115373/41548801-a022c660-732c-11e8-903f-f67370b8e6bc.png)

Can you write step by step how to do it correctly? And how did you do it?

**Comment by tomer8007** [comment]
You need additional protubuf files which I forgot to include.
Try these.
[protobuf_files.zip](https://github.com/tomer8007/kik-bot-api-unofficial/files/2112722/protobuf_files.zip)

**Comment by CheshireCaat** [comment]
@tomer8007 
Not found:
protobuf_validation.proto
google/protobuf/timestamp.proto
common_model.proto

groups/v1/groups_common.proto

How I understood, except for the last I can find everything on the Internet?

**Comment by tomer8007** [comment]
[protobuf_files_2.zip](https://github.com/tomer8007/kik-bot-api-unofficial/files/2112853/protobuf_files_2.zip)

**Comment by CheshireCaat** [comment]
@tomer8007 Thank you! It's work)

**Comment by CheshireCaat** [comment]
Autogenerated file contains errors
Should I fix it myself or is it a compilation error?

**Comment by CheshireCaat** [comment]
Example:
![image](https://user-images.githubusercontent.com/30115373/41560349-7a462e00-734f-11e8-8a70-5236dec096d0.png)

**Comment by CheshireCaat** [comment]
I try to generate Python proto, but the result is different from what is in this library

**Comment by CheshireCaat** [comment]
[group_search_service_pb2.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/2115794/group_search_service_pb2.txt)

**Comment by CheshireCaat** [comment]
Please generate csharp file for me based on how you generated your )))

**Comment by CheshireCaat** [comment]
Please help me(

**Comment by tomer8007** [comment]
I will try to compile it as soon as I will have some more time for that

**Comment by CheshireCaat** [comment]
@tomer8007 good, thanks!

**Comment by tomer8007** [comment]
Can you upload your generated C# file so I can try to understand why do you get a compilation error?

**Comment by CheshireCaat** [comment]
[GroupSearchService.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/2125312/GroupSearchService.txt)
Unknown namespaces:
Kik
Common

**Comment by tomer8007** [comment]
That's because you also need to compile the `common_model.proto` and `protobuf_validation.proto`. However `protobuf_validation.proto` does not compile for me (says it requires proto3). Anyway we don't really need it so you can try removing `global::Kik.Validation.ProtobufValidationReflection.Descriptor` from the main file.
Here is the output I got for C#.

[c_sharp_files.zip](https://github.com/tomer8007/kik-bot-api-unofficial/files/2125370/c_sharp_files.zip)

**Comment by CheshireCaat** [comment]
@tomer8007 
Thanks!!
I had to correct something, but now everything is clear and there are no mistakes
Thanks again, you really helped me!)

**Comment by tomer8007** [comment]
Is everything compiling for you?

**Comment by CheshireCaat** [comment]
After small changes - all OK

**Comment by tomer8007** [comment]
That's great
