### ISSUE TITLE
Parameters to follow

### ISSUE THREAD

**Issue by malickkz** [tomer8007/kik-bot-api-unofficial#54]
what parameters should i use on client.py?

**Comment by tomer8007** [comment]
Which parameters? Did you try one of the examples?

**Comment by malickkz** [comment]
I used -u for user and -p for pass

Sorry I'm seeing your reply this late ...

**Comment by tomer8007** [comment]
Are you talking about the command line client? Try the echo bot example

**Comment by malickkz** [comment]
Ok I will try that

**Comment by malickkz** [comment]
Hello tommer,I'm trying to use your bot to make one of my own and I need to
edit the packet sending class and add some elements like <signed>. When I
edit this part (check picture) it doesn't affect the message when sent and
it remains the same. How do you suggest I should tackle this problem?

**Comment by tomer8007** [comment]
Are you editing `IncomingChatMessage` class or something similar to that? maybe show some code

**Comment by malickkz** [comment]
I'm editing the OutgoingChatMessage in the xmpp element.

**Comment by malickkz** [comment]
I also sent an image idk why it didn't come through

**Comment by tomer8007** [comment]
Did you turn on DEBUG logs and saw it logged the same XMPP message as it would log before your modification? If you didn't, this is recommended to see what's getting sent.

**Comment by malickkz** [comment]
The debug process shows me the sent stanza and in it the <signed> doesn't
show up even though its inside the class OutgoingChatMessage (Xmpp Element)
that I edited

data = ()

**Comment by tomer8007** [comment]
This doesn't make sense. Try to corrupt the sent stanza completely. Is it still sending the same thing? If so, where does it take the stanza from?

**Comment by malickkz** [comment]
That's what I've been asking myself... xD

I'll give it a few more tries and let you know how it goes
