### ISSUE TITLE
Can't get response

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#55]
Hi
I try to use any method (get roster, find group etc) after login

Authorization is correct, I see the answer
But after sending any other request, I can not get an answer
Either it is not there, or the reading goes on indefinitely, or the reader says that the end of the stream is reached

What can be wrong?

**Comment by CheshireCaat** [comment]
Noticed an interesting moment
On some accounts the answer comes instantly and without errors, on other accounts there is no answer at all

**Comment by tomer8007** [comment]
Hmm. Do you see the second answer coming on the DEBUG log?

**Comment by CheshireCaat** [comment]
[WRITE] iq type="set" id="a2e7f315-9f85-4768-9803-a87bddbbb095"
query xmlns="kik:iq:xiphias:bridge" 
service="mobile.groups.v1.GroupSearch" 
method="FindGroups"
body CgxsZXNiaWFuczIwMTk body
query iq
System.IO.EndOfStreamException

**Comment by tomer8007** [comment]
Maybe it is because of incorrect authorization, I don't really know.
Do you have full log from the beginning?
Does it work for you in the python version (not your C# version)?

**Comment by CheshireCaat** [comment]
@tomer8007 
I use C# version
I do not know very well the Python
I tried to use the library, but I could not even authorize: D

At what this error concerns only certain actions
Authorization is always fine

Log: https://pastebin.com/6VFuSFHD

**Comment by CheshireCaat** [comment]
Sometimes it happens that there are no errors, but the read cycle from the stream is done infinitely.
If you check what you thought - there is always a blank value

**Comment by CheshireCaat** [comment]
Server always return zero bytes,
But on some accounts, it returns a normal result (rarely)

**Comment by d3vvil** [comment]
@CheshireCaat it could be that the c# version doesn't properly parse the response for the GroupSearch request. normally, an EOF error can occur when the '</k>' element is received and you attempt to read in some more data. however, since the '</k>' tag was not logged before the EOF error was thrown then that means '</k>' was never received so the stream is still active, and so that means it is not the server's fault, instead it's the fault of the client you're using.

**Comment by CheshireCaat** [comment]
@d3vvil The fact is that this applies to any other methods, whatever I take - the result I do not see

**Comment by CheshireCaat** [comment]
Has found out in what the reason, there is SafetyNet an error and the kik closes connection
How can I decide?

**Comment by CheshireCaat** [comment]
No, I did not solve the problem
Lowered the version to 11, but the answers to requests still do not come
Though when there was a SafetyNet error - were visible incoming data from the server

**Comment by CheshireCaat** [comment]
https://pastebin.com/MT3PtFZx

**Comment by CheshireCaat** [comment]
Here is the full log of work with examples
What am I doing wrong?

https://pastebin.com/ctmdxzfJ

**Comment by CheshireCaat** [comment]
I find the answer
You can close issue

**Comment by tomer8007** [comment]
What was the problem?

**Comment by CheshireCaat** [comment]
@tomer8007 
I made authorization based on the fieldswhich were transferred to another library in C#

There were only 4 basic parameters, but even with them the server replied that everything was OK
So I could not understand the reasons for the empty response error
Did all the fields as in your library - everything worked
