### ISSUE TITLE
Latest Kik HMAC

### ISSUE THREAD

**Issue by SamHoque** [tomer8007/kik-bot-api-unofficial#56]
This is the HMAC info on the latest kik version that came out yesterday (14.0) seems like they ended 13 after the 13.4 update.

Kik version: 14.0.0.11130
Classes Dex: 9nPRnohIOTbby7wU1+IVDqDmQiQ=
Hmac: zFu88/RkSPvAidkDT/JRkrUdzyY=

**Comment by tomer8007** [comment]
That's good
Did you test it?

**Comment by SamHoque** [comment]
No, I do not know how to run python programs.

**Comment by gituserdxd** [comment]
@LynxKik that's not even an issue and I'm sure @tomer8007 is smart enough to generate that himself

**Comment by SamHoque** [comment]
I don't see an issue with providing it @gituserdxd if he has a problem with it, he can say it to me you dont have to.

**Comment by gituserdxd** [comment]
@LynxKik I'm just saying this is a place for discussing issues with his code(which you don't even use or know how to run) not a wiki. You should dm him instead

**Comment by SamHoque** [comment]
@gituserdxd yes, then again it is a topic for him to talk about not you. I don't get it was your reply really needed?

**Comment by gituserdxd** [comment]
@LynxKik This "issue" wasn't needed either yet you still decide to put it out here. I dont understand why you're commenting on and forking his repo when you dont even know how to run python programs.

**Comment by SamHoque** [comment]
@gituserdxd I don't know why you are getting mad over me helping out, I can clearly tell you have no knowledge about anything in life nor know how to contribute to anything. Your username explains how immature you are and how old you actually are. I don't have to go in details how much superior I am to you, You have seen the issue okay. You don't have to go and comment in when you are are doing nothing but wasting my time, I know you have no life and can do this all day long but I can't, I have major things to work on rather then fighting with a 13 year old who knows python. this will be the last reply from this and if you are gonna say me no life for this message it took me 2 minutes to type it out. So have a nice life buddy hope god gives you some kind of knowledge in the near future :)

**Comment by gituserdxd** [comment]
@LynxKik Lmao you're a joke.  @tomer8007 you seeing this? Better close this "issue" now and block this skid trying to flex on your repos and making it look bad

**Comment by tomer8007** [comment]
This version was added to `device_configuration.py` in case anybody wants to try it.
