### ISSUE TITLE
Сaptcha at authorization

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#59]
Why does every time authorize each account, CAPTCHA appears?
Is it the Device and Android  ID or the kik's version?

     private string device_id = "167da12427ee4dc4a36b40e8debafc25";
     private string andr_id = "1fba6fa0a899e775";
     private string kik_version = "11.1.1.12218";

**Comment by tomer8007** [comment]
It's the kik version. Kik versions greater than 11 will trigger SafetyNet problems, and version 11 will trigger captchas sometimes. The way to avoid captcha is log in with a kik node once you know it.

**Comment by CheshireCaat** [comment]
@tomer8007 
I tried to find you have the code responsible for authorization on the ready node, but I have not yet seen
If I do this, do I have to skip any steps when authorizing?

**Comment by tomer8007** [comment]
If you do what? I don't understand.

**Comment by CheshireCaat** [comment]
Auth with node by default

**Comment by tomer8007** [comment]
I you do that on version 11 than it doesn't require captcha. at least this is what happens in experiments.

**Comment by CheshireCaat** [comment]
@tomer8007 can you show me login example with node?

**Comment by tomer8007** [comment]
just look at the `KikClinet `constructor's docsting. once you get the node you supply it as the third argument.

**Comment by CheshireCaat** [comment]
I do it, thanks)
