### ISSUE TITLE
Getting Group Members

### ISSUE THREAD

**Issue by Hawk120** [tomer8007/kik-bot-api-unofficial#60]
Is there a way to get a list of Group members ? When I apply  request_roster the Output is like: 
Roster:
Group(jid=[jid]_g@groups.kik.com, name=Test Group, code=#justtestit, members=7)
Nxxx Hx (nxxx_xx_xx)
Kik Team (kikteam)

But I dont get a list of the (seven) members of the group

**Comment by tomer8007** [comment]
Are you getting only one of them? [The code](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/peers.py#L28) says you should get them all.

**Comment by Hawk120** [comment]
Actually I am not getting any of them, All it tells me is the above. The Users Nxxx Hx and Kik Team are users I have talked to before. But its not giving me any of the Group members. I am using the example Code to send roster query and fetch the answer:

self.client.request.roster()  # to start the query

def on_roster_received(self, response: FetchRosterResponse):
        print("[+] Roster:\n" + '\n'.join([str(m) for m in response.members])) # to get the answer


As for the group this is all I get:
Group(jid=1100227639403_g@groups.kik.com, name=Test Group, code=#justtestit, members=9)

**Comment by tomer8007** [comment]
Can't you iterate over the `members` filed?

**Comment by XenXenOfficial** [comment]
How would you go about in iterating over the members field?
Im tryin to do 
`members = [i for i in response.group.members.is_admin]
        print(members)`
But nothing is popping up, and when i go through the `members` field it shows object locations

Like if i have 3 members it would show 3 object locations, and if i have 47 members, it'll show 47 object locations

**Comment by XenXenOfficial** [comment]
I now got it to say "True" or "False" depending on if the member is an admin or not, but it's not exactly what i want :/

**Comment by XenXenOfficial** [comment]
I added in `users = data.findAll('m')` into the `peers.py` file then called that with `response.group.users`, it's now giving me the outcome I was expecting.

Edit: When i do it in a publicly available group it does None. I'm confused now.

**Comment by tomer8007** [comment]
I've commited a new change to `FetchRosterResponse` to make the name `members` less confusing.

The roster you get has a list of `peers`, and when one peer is a `Group`, its `memers` field is a list of `GroupMember`s. Please take a look at the [relevant classes](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/peers.py#L28).

**Comment by Hawk120** [comment]
Thank you for your help and I see what you did. I am just not an expert yet on python. I changed the Code in the peers.py and roster.py but the System doesn't care. Even if I create an error on pupose by inserting a line like "jhkjhjhkjh" it still runs. It seems as if somehow the import does not import the new Version at all... I am Kind of lost

**Comment by tomer8007** [comment]
Why did you change the code in `peers.py` and `roster.py`? I thought you were able to insret `users = data.findAll('m')` earlier.

Anyway, I understand that your problem now is that you can't iterate over member in public groups, right? Please post some code so I can understand it better.

**Comment by XenXenOfficial** [comment]
I'm the one that added the `users.findAll('m')`, his issue (I believe) is that the system isn't loading up the peers file

**Comment by tomer8007** [comment]
Oh oops

**Comment by tomer8007** [comment]
@Hawk120 Are you trying to iterate over the `memebrs` field in groups?

**Comment by XenXenOfficial** [comment]
Naw he isn't, I am. 

He's wondering why the system still runs the file even after artificially creating an error by including a jumble of letters in one of the files.

**Comment by tomer8007** [comment]
@XenXenOfficial What code do you use to iterate memebrs in public groups?

**Comment by XenXenOfficial** [comment]
@tomer8007 I just added the `users = data.findAll('m')` and then I'm grabbing that value in my response roster

**Comment by Hawk120** [comment]
Ok I fixed my problem with the code. @XenXenOfficial  can you send me your code or tell me what you did ?

**Comment by Hawk120** [comment]
I haven't tried it yet since I am not near my Computer. But shouldnt a line in the Peers.py likethis work:
Self.users = ( x.gettext() for x in data.findall(‚m‘))

I am not very familiar with bs. So I dont know if the function would be gettext() or get_text()
But shouldn't this fork ? I will try it the other day.

**Comment by tomer8007** [comment]
@XenXenOfficial You don't really need to add that `users` line, there's already a `peers` field specifically for this purpose. in case one of the `peers` is a `Group` you can access its `memebers` field.

**Comment by sapiosaurus** [comment]
Not to horn in on the chat, but how can you map a username from a group (ajgmqljb6lvdppc3z2pkyoysa7hnajycb2jwd6wlqkls22o24fea@talk.kik.com) to a username or "full name" ?

**Comment by tomer8007** [comment]
@drmarvel Do you have the `User` object? I see that there's a 'full name' field [here](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/datatypes/peers.py#L11).

**Comment by sapiosaurus** [comment]
Is a User object inherited by a GroupMember class? I can't seem to access it when pulling the roster (besides accessing the GroupMember jid)

**Comment by tomer8007** [comment]
Oh, I understand. How about [request_info_of_jids](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L179)?

**Comment by sapiosaurus** [comment]
Absolute facepalm moment right now. Thank you so much.

**Comment by Hawk120** [comment]
Ok, @drmarvel @tomer8007 , you totally lost me. I managed to get the jid of the users of a Group. But how can I use that for the user object ? The user object is called with peer not jid

Using request_info_of_jids I only get some strange number as Output.... Can you help ?

**Comment by tomer8007** [comment]
Are you using the `on_peer_info_received` callback? You're getting there `User` objects eventually.

**Comment by Hawk120** [comment]
No I am not yet. Cause I dont have peer info.. I have a jid of a member like xxxdtcfjvb4hpq3lxzwf2zti4efbjjyvjdn3zuqlby6i6ss7a62a_a@talk.kik.com


And I would like to get the user Infos for that jid.

I can't figuere out how to get the user Infos for an existing jid

Kind of lost but I think I have to think About a few more moments

**Comment by XenXenOfficial** [comment]
Hey tomer! Would you know how i could grab the group members anytime without waiting for the `roster` call?

Edit:
Tbh, all i wanna do is check if the user that sent a message is in the `is_admin` field

**Comment by tomer8007** [comment]
@Hawk120 What strange number do you get? you're supposed to call `request_info_of_jids` and then inside the callback `on_peer_info_received` you get the `PeerInfoResponse` object.

@XenXenOfficial Maybe try `request_info_of_jids` for the JID of the group? I'm just guessing

**Comment by ether8unny** [comment]
or look for a = 1 before the jid

**Comment by sapiosaurus** [comment]
Be careful using request_info_of_jids on the group JID, it typically results in a connection closure.

to enumerate group users, call a roster:
for var in response.members:
            if self.client.is_group_jid(var.jid):
                for member in var.members:
                    user = self.client.request_info_of_jids(member.jid)

Then in the on_peer_info_received callback, use:

user = response.users[0] (this retrieves the latest user gathered from self.client.request_info_of_jids

**Comment by sapiosaurus** [comment]
You can then access everything except for username (display_name, and group specific jid) from the "user" variable (or response.users[0])

The batch enumeration of users wasn't super consistent on kik's side, so I've switched to doing them one by one.

**Comment by Hawk120** [comment]
@drmarvel : Thanks for your help. But I dont seem to get it. When I call a roster and try to use response.members I get an error. It says the string Response has no Attribute members

**Comment by tomer8007** [comment]
The `FetchRosterResponse`'s `memebrs` field is now called `peers`.

**Comment by Hawk120** [comment]
Ok, working fine now. Unfortuanetly the Username can't be retrieved though. But I think I can work with the encrypted jid too.

**Comment by Hawk120** [comment]
@tomer8007 : I think the thread can be closed
