### ISSUE TITLE
Verify kik account

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#62]
Hi, How i can do this request?
https://github.com/tomer8007/kik-bot-api-unofficial/issues/19

what is signature and kik-pub-key

at what point should I create this request?
I need it to group joining

**Comment by tomer8007** [comment]
I don't understand what are you trying to do. What do you mean by verify an account?

**Comment by CheshireCaat** [comment]
I want use this request:

https://pastebin.com/XgayMD75

because when i try to join on some accounts - server retutn "bad-request" error
and  account does not joining to the group

as I understood - the problem is in this
if I'm wrong - correct me
on what does the opportunity to join the group depend?
By the way, I tried to make join on some accounts manually from my phone - some come out, some do not

I apologize for the bad english)
I use google translator))

**Comment by tomer8007** [comment]
Do you have a DEBUG log that show the error you get when trying to join a group?
Also, where do you see this `kik-pub-key`?

**Comment by CheshireCaat** [comment]
@tomer8007 log - https://pastebin.com/x4xut0sZ
I see it in request body from issue #19 
![image](https://user-images.githubusercontent.com/30115373/43652842-09b9d08c-974f-11e8-8daf-f1fded0c1b36.png)

**Comment by tomer8007** [comment]
If I understand you correctly, You're trying to verify your account so that you can join a group. otherwise joining a group returns a 400 error. right?
But I don't see that `kik-pub-key` in the pastebin you posted. When is it sent/received?

**Comment by CheshireCaat** [comment]
@tomer8007 
No)
I'm having this error in the join request

I started looking for an answer in the existing issues
Has foun issue #19 

There you talked about the need to pass through Antispam using a request with this two parameters (at the very end)
I became interested in this, and wanted to know how this query is built and where it should be applied

![image](https://user-images.githubusercontent.com/30115373/43655462-61fb9dcc-9757-11e8-9dc6-4f348b55ebb4.png)

**Comment by tomer8007** [comment]
I'm just not sure where is the `kik-uuid` request. I don't it getting sent [in the code](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client_legacy.py#L313) when joining a group.

**Comment by CheshireCaat** [comment]
@tomer8007 
In general, the main problem:

I use one account - the server does not return an error. I go to the same account from the phone - he successfully joined the group

I'm using another account - the server returns an error. I go to the same account from the phone - he did not join the group.
In addition, when I try to join a group manually - the account also does not enter to group

What determines the success of the entry?
How to avoid this problem?

**Comment by tomer8007** [comment]
Oh, I think I understand. You're asking where the `kik-uuid`/`signature` request is built or sent. Unfortunately I don't know the answer. I can only repeat what @edroot has said: This problem exists only for accounts that did not pass the anti-spam check. And probably the way to pass this check is to get your account verified via the `signature` request, which I do not know how to generate.

Maybe you should try to see if joining a group works when the account was created from a real device. I don't know the exact conditions for this, but this can be tested with trial and error.

**Comment by CheshireCaat** [comment]
@tomer8007 
Ok, Thanks!
I will test it
If I find a solution, I'll tell you

**Comment by tomer8007** [comment]
OK, cool
