### ISSUE TITLE
Join group return error code 500

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#63]
When i try to join to any group, server return this response:
https://pastebin.com/df4jmCm8
Why does this error occur and how to avoid it?

**Comment by tomer8007** [comment]
I did not encounter this error on the past so I'm not sure, but as the XML says that's internal server error from kik's servers.

So what I would do is do some trial and error to see under which conditions this error is returned and on which not (try different accounts, etc)

**Comment by CheshireCaat** [comment]
@tomer8007 Can you tell me in detail how to get traffic from kik?
I tried to use wireshark on win 8.1 - nothing happened
I put a virtual machine, installed ubuntu, tried to use mitmproxy - nothing happened, what should I do?

**Comment by tomer8007** [comment]
Check out [this issue](https://github.com/tomer8007/kik-bot-api-unofficial/issues/5), which I explain how to do that.
