### ISSUE TITLE
Interactive_client example not fethcing peers.

### ISSUE THREAD

**Issue by vindu939** [tomer8007/kik-bot-api-unofficial#66]
When I run the interactive client code and type `/f` it just sends the roster request but never receives an response. I can only see the following log and nothing after that. Can you please help me with whats the issue.
```
[2018-08-11 21:27:19,387] INFO   (thread Kik Connection): [+] Authenticated successfully.
-Usage-

/c [first letters of username]  -  Chat with peer
/f  -  List peers

Type a line to send a message.

/f
[2018-08-11 21:28:11,731] INFO   (thread Kik Connection): [+] Requesting roster (list of chat partners)...

```
Although `echo_bot` and `register_client` are working fine

**Comment by vindu939** [comment]
Its all because of the while loop

**Comment by tomer8007** [comment]
Yes, thanks for reporting. I moved the `chat` method to a new thread and now it's not blocking. You can download the latest commit.

**Comment by vindu939** [comment]
That's super quick :)
