### ISSUE TITLE
Error during Sign-UP with captcha

### ISSUE THREAD

**Issue by maestron** [tomer8007/kik-bot-api-unofficial#69]
What is the format of the captcha result as done by the example expected to be?

The response token from the KIK server looks something like this:

`
xxxxxxxxxxxx.xxxxxxxxxxxxx|r=us-west-2|metabgclr=transparent|metatimeclr=%xxxxxx|meta=x|guitextcolor=%xxxxxx|metaiconclr=transparent|lang=en|pk=xxxxx-xxxxx-xx-xx-xxxx|injs=https://cdn.funcaptcha.com/fc/assets/graphics/kik/scripts/kik_help_8.js|at=xx|ps=id|ht=x|atp=x|cdn_url=https://cdn.funcaptcha.com/fc|lurl=https://audio-us-west-2.funcaptcha.com|surl=https://funcaptcha.com`

I tried inputing all of it with no success.

**Comment by tomer8007** [comment]
Yeah, that was the wrong request.
As the instructions say, the request should start with `https://kik.com/captcha-url`
