### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by maestron** [tomer8007/kik-bot-api-unofficial#70]
Is there proxy support?

**Comment by tomer8007** [comment]
Do you mean like a SOCKS proxy? The API does not natively support proxies, but it should be as easy as modifying the target server address in `client.py` and then forwarding the packets to the real server in your proxy.
Is that acceptable?

**Comment by maestron** [comment]
yeah I figured that would be the way. Its complicated because its TCP protocol and can't use HTTP proxies.

**Comment by maestron** [comment]
Are you available for hire? How can you be reached?

**Comment by tomer8007** [comment]
@maestron Not available for hire :-(
