### ISSUE TITLE
ImportError: cannot import name 'Utilities'

### ISSUE THREAD

**Issue by leotorrez** [tomer8007/kik-bot-api-unofficial#77]
PS C:\Users\LeandroFabian\kik-bot-api-unofficial\examples\legacy> python .\send_message_legacy.py
Traceback (most recent call last):
  File ".\send_message_legacy.py", line 4, in <module>
    from kik_unofficial.client_legacy import KikClient
  File "C:\Users\LeandroFabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kik_unofficial\client_legacy.py", line 14, in <module>
    from kik_unofficial.utilities import Utilities
ImportError: cannot import name 'Utilities'

Would someone mind to lend me a hand?

**Comment by tomer8007** [comment]
Nice catch. I've commited a fix for this bug.
However, note that `client_legacy.py` is old and is likely to have more problems in the future. For example, now it produces "account suspened" when trying to log in.

It's recommended to try the `echo_bot.py` example.

**Comment by leotorrez** [comment]
Thanks a lot for your response! I am using that one as it was working properly and i found it easier to understand. I'm new in python and this project its helping me learn it quite quickly
