### ISSUE TITLE
OutgoingGroupIsTypingEvent

### ISSUE THREAD

**Issue by leotorrez** [tomer8007/kik-bot-api-unofficial#78]
For some reason i have some issues with it

self.client.send_is_typing(peer_jid=givers_jid, is_typing=response.is_typing)

that's my code where "givers_jid" is the id of a group and i'm taking the "is_typing" from another group.

however it does not give me an error and does not show the bot as typing on the "givers_jid" group. The bot can send messages to that group using that same jid. Maybe i'm not using the function properly?

**Comment by leotorrez** [comment]
Quick update. I tried to modify the file chatting.py so it turns the bool into a string just in case.... and still not working.

What i'm trying to make its communicate two groups in kik using the bot as an entity that passes messages from one side to the other.

In simple words
if FROM=A 
    SEND TO B
if FROM=B
    SEND TO A

and thats working just fine with the proper python code.

what i wanted to add its that when someone is writting in A it shows the bot writting in B. And viceversa.

**Comment by tomer8007** [comment]
Why turn a boolean into string? `send_is_typing` expects a boolean (True if typing, False is not).
Did you try testing this function on a regular personal chat?

Also, is there anything unusual in the DEBUG log (which shows exactly the raw data that was sent and received)?

**Comment by leotorrez** [comment]
Sorry what i modified is not the boolean in send_is_typing. I modified the following:

> class OutgoingGroupIsTypingEvent(XMPPElement):
    def __init__(self, group_jid, is_typing):
        super().__init__()
        self.peer_jid = group_jid
        self.is_typing = is_typing

    def serialize(self):
        timestamp = str(int(round(time.time() * 1000)))
        data = ('<message type="groupchat" to="{}" id="{}">'
                '<pb></pb>'
                '<kik push="false" qos="false" timestamp="{}" />'
                '<is-typing val="{}" />'
                '</message>').format(self.peer_jid, self.message_id, timestamp, str(self.is_typing))
        return data.encode()


The line before the last. Also i didnt knew there was a DEBUG log lol. I am new in python so there's stuff i am unaware. I will try to figure out where is it

**Comment by leotorrez** [comment]
I made my own debug method lol. I added a print(data.encode()) on the call OutgoingGroupIsTypingEvent ()

Then i went to the group.... wrote a bit and then stopped and got these


[+] alebgnqxna6mbsoofajpcrajqpifvrcp3wrqg5hdrdsancpecerq_a@talk.kik.com is now typing in group 1100229373572_g@groups.kik.com
b'<message type="groupchat" to="1100229373682_g@groups.kik.com" id="5f5b6b89-01a9-47d6-b39c-e8522c89c3ba"><pb></pb><kik push="false" qos="false" timestamp="1538099650115" /><is-typing val="True" /></message>'
[+] alebgnqxna6mbsoofajpcrajqpifvrcp3wrqg5hdrdsancpecerq_a@talk.kik.com is now not typing in group 1100229373572_g@groups.kik.com
b'<message type="groupchat" to="1100229373682_g@groups.kik.com" id="f0f7d325-3960-4d49-b3e6-8085ecd01409"><pb></pb><kik push="false" qos="false" timestamp="1538099707784" /><is-typing val="False" /></message>'

**Comment by leotorrez** [comment]
sorry im new in git too....
```
[+] alebgnqxna6mbsoofajpcrajqpifvrcp3wrqg5hdrdsancpecerq_a@talk.kik.com is now typing in group 1100229373572_g@groups.kik.com
b'<message type="groupchat" to="1100229373682_g@groups.kik.com" id="1c83ca8f-527d-4525-861f-394672691ab3"><pb></pb><kik push="false" qos="false" timestamp="1538100052013" /><is-typing val="True" /></message>'
[+] alebgnqxna6mbsoofajpcrajqpifvrcp3wrqg5hdrdsancpecerq_a@talk.kik.com is now not typing in group 1100229373572_g@groups.kik.com
b'<message type="groupchat" to="1100229373682_g@groups.kik.com" id="d452da19-fd8f-47dc-aa0f-59fc2abb7354"><pb></pb><kik push="false" qos="false" timestamp="1538100052025" /><is-typing val="False" /></message>'
```

**Comment by leotorrez** [comment]
Welp.... Good news its i figured it out.

The value is-typing its expecting a lowercase string. So a simple str(self.is_typing).lower() did the trick.....

Thanks for taking your time on reading lol. And i think you should add that fix to your code too

**Comment by tomer8007** [comment]
Absolutely. You can now use the updated version.
Thank you for this nice bug catch!

By the way the DEBUG log I was talking about is generated when you pass `log_level=logging.DEBUG` to the `KikClient` constructor.

**Comment by leotorrez** [comment]
Yeah i figured that out a bit late when i was reading the code and saw the function log() lol... still thanks a lot!
