### ISSUE TITLE
Cant sent several messages with delay between them

### ISSUE THREAD

**Issue by arty2203** [tomer8007/kik-bot-api-unofficial#79]
I'm trying to make a bot which sends a bunch of messages, with some pause between each other, by modifying EchoBot. Unfortunately, i'm new to Python, and possibly doing it wrong. Bot code is following:

` def on_chat_message_received(self, chat_message: chatting.IncomingChatMessage):
        print("[+] '{}' says: {}".format(chat_message.from_jid, chat_message.body))
        print("[+] Replaying.")
        self.client.send_chat_message(chat_message.from_jid, "Hi!")
        sleep(5)
        self.client.send_chat_message(chat_message.from_jid, "This is my bot")
        sleep(10)
        self.client.send_chat_message(chat_message.from_jid, "And his answers are delayed")`

In script output i can see that messages are sent with delays:
`[2018-09-29 03:44:25,370] INFO   (thread Kik Connection): [+] Sending chat message 'Hi!' to user 'hdoe333_6w4@talk.kik.com'...
[2018-09-29 03:44:30,375] INFO   (thread Kik Connection): [+] Sending chat message 'This is my bot' to user 'hdoe333_6w4@talk.kik.com'...
[2018-09-29 03:44:40,387] INFO   (thread Kik Connection): [+] Sending chat message 'And his answers are delayed' to user 'hdoe333_6w4@talk.kik.com'...`

But recipient gets them all at the same time, after longest sleep is over (in the example above he'll get all 3 messages after 10 seconds)

**Comment by tomer8007** [comment]
Yes, that's because right now callbacks are called on the `Kik Connection` thread, which means that everything that's done inside them basically blocks network operations.

As a workaround you can do this logic in a new thread (`from threading import Thread`).

**Comment by arty2203** [comment]
Can you please give more detailed example?

**Comment by tomer8007** [comment]
Like [that](https://stackoverflow.com/a/2906014/1806873)?

**Comment by arty2203** [comment]
Got what i need via threads. Thanks for help.
