### ISSUE TITLE
Getting users in a group

### ISSUE THREAD

**Issue by CarbonNeuron** [tomer8007/kik-bot-api-unofficial#8]
I need help getting the users in a group, whenever I try I get an error, please help.

**Comment by tomer8007** [comment]
OK, i'm trying to fix this. Can you post example code?

**Comment by CarbonNeuron** [comment]
I can post example code in a few minutes. I may be doing something wrong, is why I'm asking.

**Comment by CarbonNeuron** [comment]
`import sys
import time

from kik_unofficial.kikclient import KikClient
from kik_unofficial.kikclient import KikCryptographicUtils
username, password = "username", "password"
kik_client = KikClient(username, password)
print("[+] Listening for incoming events.")
#while True:
        
element = kik_client.get_chat_partners()['1100220388995_g@groups.kik.com']['users']
for i in range(len(element)):
    var = dict(element[i])
    var = var['jid']
    var = var[:len(var)-17]
    print("user #{}: {}".format(i,var))`
this will output the group's user's usernames.

**Comment by tomer8007** [comment]
`get_chat_partners` is meant for getting your chats list (roster). You should use `get_info_for_group` if you want to get the users of a particular group.

Does `get_chat_partners` even returns useful data for you?

**Comment by CarbonNeuron** [comment]
I updated my post.

**Comment by tomer8007** [comment]
Wait. Are you trying to get group memebers or list of chats? 
Is the problem the absence of JIDs in your output?

**Comment by CarbonNeuron** [comment]
Im trying to get a list of users that are in the group chat. When I tried to use your commands, I get an error.

**Comment by CarbonNeuron** [comment]
what should I put in for get_info_for_group?

**Comment by CarbonNeuron** [comment]
I am specifically removing the jid, i want to output it to a ini file. im probably going to get user information and index it in that ini file. I just need to get the usernames first.

**Comment by tomer8007** [comment]
I'm looking into it.

**Comment by CarbonNeuron** [comment]
ok cool.

**Comment by tomer8007** [comment]
Well, the `get_info_for_group` method essentially does a group search and the group's `code` (the function's  parameter) is actually the group's hashtag (like "#MarioKart").

Unfortunately the current code does not handle this method very good (It also does not parse the server's response properly). I am going to upload a newer version soon (hopfully tomorrow).

Anyway, `get_info_for_group` should return the group's display name, profile image, and information about its users.

**Comment by CarbonNeuron** [comment]
is there any way to get that info for a group that is private? and is there a way to find out which users are admin? Also, for a suggestion: add a way to send the message formats in the wiki, ie, give it the codes from the wiki and it will send it to the kik servers

**Comment by tomer8007** [comment]
Yes, I will try to work on that. Currently I do not see a message format on the wiki for getting info for private groups, so I will need to investigate this.

**Comment by tomer8007** [comment]
Okay, you can now try the latest code from GitHub, but it still lacks the abillity to get info for private groups. I will add that later.

**Comment by CarbonNeuron** [comment]
Ok cool! Thanks! Maybe the code I posted here could be useful to you when you are getting info for private groups! How do I use the message formats in the wiki? Do I just use the makerequest and get response functions?

**Comment by tomer8007** [comment]
Actually I think most of the useful stuff on the wiki are already implemented/parsed. From what I've seen only group adminship operations and username validating operations are not implemented yet. Which message do you plan to use?

And yes, you are supposed to just use `_make_request` and `_get_response` to send them. (If you get empty response try `_get_full_response`).

**Comment by CarbonNeuron** [comment]
Haha, I'm mainly talking about the group adminiship options. (Making a auto administratior for my group)

**Comment by CarbonNeuron** [comment]
What would the real response be for those admin operations? Just if it was a success or failure?

**Comment by tomer8007** [comment]
I'm not sure what the real responses will exactly be because I didn't try it. It's probably just a kik `error` element in the case of a failure. The best way to tell is to test. 

If you get it working maybe post some code so that it'll get added to the API faster. Most of the functions should be pretty trivial to implement I think.

**Comment by CarbonNeuron** [comment]
You could probably make a function for it,
```python
def groupAction(chatjid,action,user)
```

**Comment by CarbonNeuron** [comment]
Will try and work on it! Btw, the underscore to my knowledge means private, ie if you name a variable _variable it means it is a private variable. The functions for make request looked private!

**Comment by tomer8007** [comment]
Yeah, they should be private.

**Comment by CarbonNeuron** [comment]
Ok! I will try and work on the group administration stuff. Will get back to you when I finish it! Thanks for your help.

**Comment by tomer8007** [comment]
Awesome.
