### ISSUE TITLE
Establishing sessions

### ISSUE THREAD

**Issue by SamHoque** [tomer8007/kik-bot-api-unofficial#81]
I'm writing a client that connects to kik servers via java, I got the most part down.

-Connections
-Sockets
-Crypto/Encodings
-XMPP Handlers
-Send and receive responses

I'm having some issue when trying to establish a session after logging in, After a successful login and receiving the user data back from the server I try to establish a session but the server does not `ok` the session for some weird reason, It's not an issue with my sorting or the data I'm sending I have tried to send the output made from the python lib you have created using my java client and it still does not `ok` the session after a successful login attempt, I have already tried to just send the connection payload for establishing sessions without sending any data and it still does not `ok` the session this is what I receive when I try to establish a session

`<k ok="0"><noauth><msg>Not Authorized</msg></noauth></k>`

I checked how kik handles this error and it throws an exception the exception is not really helpful because it tells me to check my login info, if my login info was incorrect the server wouldn't even send me valid information after I send the login stanza, I have been trying to debug this for about 4 days now and decided to ask you for help since you already have dealt with this. I think my problem is because I need to use a special socket or something. I'm currently using SSLSockets.

**Comment by tomer8007** [comment]
Does the original python client still work for you? What I whould do is just compare the python and java line-by-line, as long as the python client is still working.
If I understood corretly, you are unable to get an `ok` response after sending `EstablishAuthenticatedSessionRequest`. Correct?

Also, from the `Not authorized` error I think the device IDs could be the source of the problem.

**Comment by SamHoque** [comment]
Yes the python client works for me, What I tried to do to make sure It's not my code messing up i have printed out the connection payload created by the Python lib and then establish a session using that connection payload in my java client, And it still does not sends an `ok` response, So I don't think device ID is the source of the problem because when I hardcode the same connection payload in your python client and send it to kik server the server `ok`'s the session so I think it has something to do with the socket or output stream of my client?

this is how I'm doing it the socket and writer

```
private SSLSocket sslsocket;
private BufferedWriter bufferedWriter;
```

//set it up
```
sslsocket = (SSLSocket) SSLSocketFactory.getDefault().createSocket(kikHost, kikPort);
bufferedWriter = new BufferedWriter(new OutputStreamWriter(sslsocket.getOutputStream()));
sslsocket.startHandshake();
sslsocket.setKeepAlive(true);
```

//method to send the data
```
private void write_to_kik_server(String data) throws IOException {
  bufferedWriter.write(data);
  bufferedWriter.flush();
}
```

**Comment by SamHoque** [comment]
I'm trying to do this, as you mentioned the method name yes. https://github.com/tomer8007/kik-bot-api-unofficial/blob/3411de55930b6717bfb576adf756ff8c8abd8f67/kik_unofficial/datatypes/xmpp/login.py#L71

I have printed out the `packet` this method creates and hardcoded it and sent it both via my java client and your python client, It works everytime with the python client and doesn't work even once with my java client.

**Comment by tomer8007** [comment]
You could try comparing raw network traffic by putting an SSL proxy like [sslsplit](https://github.com/droe/sslsplit).

**Comment by gituserdxd** [comment]
Establish a session with just your node no need to login or fake a device. If you're still unable to establish a session then you obviously don't understand how signed= value is generated. also @tomer8007  I thought this place was about issues regarding your client not stackoverflow for copy pasters...

**Comment by SamHoque** [comment]
@gituserdxd I don't believe you have read through the issue else you wouldn't miss what I have said, Just quoting from what I have said earlier:

> What I tried to do to make sure It's not my code messing up i have printed out the connection payload created by the Python lib and then establish a session using that connection payload in my java client, And it still does not sends an ok response

so I do not understand where you got the idea that 

> then you obviously don't understand how signed= value is generated

because I sent the data to the servers of what the python lib generated using my java client and I was still unable to establish a session, I printed out my node aswell by hard coding the UUID and timestamps and they printed out the exact same result on both python and java. So I don't believe It's the node, I am just guessing It the socket or java is sending extra data along with the node.

**Comment by gituserdxd** [comment]
@LynxKik did you try a different uuid? Also its wrong to hardcode timestamp because kik can possibly restrict users if they see so many of them logging in with the same timestamp tomer gave. I even told tomer this and shared my code for generating appropriate current time in millisecond for the session. If you wanna look at it check it out on my profile. And regarding the signed= value its the most challenging part when writing your own kik client I know because I also have a java client so i assumed you had the same problem

**Comment by tomer8007** [comment]
@LynxKik I think it can be helpful if you would post the code in both java and python that sends the hardcoded packet or something reproducable that shows the problem so we can debug this. 

I don't know what could go wrong using `SSLSocket` in java. Did you try sending a hardcoded packet multiple times with pytohn too? The idea that java is sending extra bytes along the node doesn't make a lot of sense to me. But if you think it's communication-related you can use SSL sniffers or so.

**Comment by SamHoque** [comment]
Yes, I will make my java client open source in a few, I just woke up.

**Comment by SamHoque** [comment]
Okay, I have my project up on github. Here is the Link https://github.com/LynxKik/LynxKikApi the main class is LynxClient, I have already included the hardcoded version and a set of username and password that works for you to test out.

**Comment by SamHoque** [comment]
Okay so I didn't touch the code ever since I made this issue, I decided to touch the code again today, I managed to fix the error. The error was so an one off error. I wouldn't even have figured it out but for some reason my mind kept telling me it was that, So I tried to change that and it worked.

Long story short: I was logging in with kik version 14.8, and then trying to establish a session with kik version 14.5. Which caused the whole error. You may now close this issue, Thanks for your time! :)

**Comment by SamHoque** [comment]
Since this issue is still open, I am having another problem the inputstream closes at random times, or after a few minutes of being inactive, The input stream is returning `-1` Have you ran into this issue before or know why its doing this?

**Comment by tomer8007** [comment]
@LynxKik Nice to hear the original problem is now solved. Now, What do you mean by the input stream returns `-1`? Do you mean that kik closes the connection unexpectedly? If that's the case it would be quite hard to tell what's causing this without an example of a situation where it doesn't happen.

**Comment by SamHoque** [comment]
Kik closes the connection unexpectedly yes, It happens at random time, It can happen when i am sending some message XMPP or just a few minutes of being inactive.

**Comment by SamHoque** [comment]
Hi, I seen kik send XMPP responses such as `ack` and `ping`, Do you send any response per x amount of time to keep the connection open?

**Comment by tomer8007** [comment]
All I can remember is [this piece of code](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L261).

**Comment by SamHoque** [comment]
I see the code needs to be Synchronized? I called `currentMillis()` instead of Kik's Synchronized timestamp generator or even their UUID generator and it would cut the connection right as I send that XMPP.

**Comment by tomer8007** [comment]
Yes, there's that algorithm for generating timestamps. I never realized they did that for synchronization.

**Comment by SamHoque** [comment]
It's for the UUID aswell, Well making the WHOLE program `Synchronized` would be a bit tricky. How do you retrive data that was sent when the program wasn't running? Because message XMPP dont get pushed to me when I start the program and messages were sent to me before I start the program,

**Comment by tomer8007** [comment]
Wait, what do mean by `Synchronized`?

**Comment by SamHoque** [comment]
Keep the whole program in the same thread and run code after each other instead of running parallel code

**Comment by SamHoque** [comment]
Okay so I debugged it more, and I dont get an empty response it server just closes the socket. I tried to send data when I receive `-1` as data this is what I get

`java.net.SocketException: Connection closed by remote host` verifying the socket is closed.

**Comment by SamHoque** [comment]
Okay so far the client does not CLOSE if I dont send XMPP back to the server so I messed up making it thread safe or what ever, but how ever I get this error after a bit.

> java.net.SocketTimeoutException: Read timed out

**Comment by SamHoque** [comment]
Also got this error after a few minutes of running the program.

> java.net.SocketException: Software caused connection abort: recv failed

**Comment by tomer8007** [comment]
From my experience in pyhton when kik servers close the connection it's because they don't like some parameter you sent (perhaps cryptographic), but I don't know the details of your Java software to really tell.

**Comment by SamHoque** [comment]
@tomer8007 the source code is up on my github page, I will do a push in a bit with my latest code. Maybe you can take a look?

**Comment by tomer8007** [comment]
Umm I don't see anything obviously wrong with your code. If I understand correctly, it basically works but kik sometimes closes the connection unexpectedly at random times, right? Did you try to see if the problem exists in the python client too? if that's the case then we can be sure that it's something that's common to both codes. If it isn't, do you suspect a change you made recently to be the cause (did it work before)?

**Comment by SamHoque** [comment]
Yes that is correct, No it never happened to me on your python lib. I don't code in python so I didn't look at your code and do an one to one copy, I just saw how the socket was connecting and wrote my self a code with a BufferedReader/Writer. But yeah the issue only happens on my code.

**Comment by tomer8007** [comment]
OK then my next thought would be to compare the inital session establishment XMPP requests.
But really the most important thing is to reproduce the problem reliably so you can tell what's working and what's not. After a successful login, is it enough to do nothing but to wait in order to see the disconnection? If it's enough than how long does it take?

**Comment by SamHoque** [comment]
After a successful login, I can receive messages and such XMPP. How ever after like 2 minutes of no response back and forward the connection closes and throws this error `java.net.SocketException: Software caused connection abort: recv failed`

**Comment by tomer8007** [comment]
So if you login, then wait 2 minutes, it always throws this exception?

**Comment by SamHoque** [comment]
Yes, The time is always a few offsets. It's not EXACT 2 minutes.

**Comment by tomer8007** [comment]
And I suppose this does not happen when you do exactly the same with the python client?

**Comment by SamHoque** [comment]
It does not correct.

**Comment by tomer8007** [comment]
It does happen?

**Comment by SamHoque** [comment]
It only happens on my java client, and not the python client. There is some issue with my code that I can't identify it's most likely an one off error.

**Comment by SamHoque** [comment]
I have pushed my latest code, I still can't fix the random disconnect issue, If you have the time can you look into it?

**Comment by tomer8007** [comment]
My thoughts about how to find the cause of this problem is this:
1) Since you said the problem doesn't exist in the python client, than it should be something to do specifically with the Java implementation.
2) Since kik servers close the connection, it's probably because the java client didn't do something that the python client did which is related to the actual network data being sent.
3) Did you implement [this functionallity](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L272) in your client? This is, by the comments, some kind of keep-alive that sounds like a possible cause indeed. However it says it happens every half an hour and you're saying that it disconnects after 2 minutes.

So what I would do if I was you is:
1) Run the python client with DEBUG logs turned on for 3 minutes.
2) Then run the Java clinet with logs inside the `write_to_kik_server` method, for 3 minutes. Make sure it really disconnected after ~2 mintues.
3) Compare the results. Check if there are packets missed up or a missing parameter somewhere. 

Another guess (not sure about it): Did you implement [multi-packet data](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/client.py#L428)?

**Comment by SamHoque** [comment]
I switched to a diff laptop, now it doesn't disconnects after 2 minutes. Not sure what's wrong

**Comment by tomer8007** [comment]
Too weird.

**Comment by SamHoque** [comment]
Well, I'm making a desktop messenger for kik, So I will have to catch this when it disconnects. Can you tell does kik resumes a session after login in? if the wifi goes out or does it create a new session? because establishing a new session requires the users password again, How does kik store the password? or can we just resume a session if so have you done it?

**Comment by tomer8007** [comment]
Is your problem having to request the user's password every time? You can store a hash-like version of the password that can be used for logging-in/establishing a session with `key_from_password` function, [here](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/utilities/cryptographics.py#L20).

**Comment by SamHoque** [comment]
No, That's not the problem, I am just curious how kik does it so I can do it officially aswell. I don't think kik stores a hash version?

**Comment by tomer8007** [comment]
You mean like how do kik servers know your password was right when you log in?

**Comment by SamHoque** [comment]
No, Lets say I have logged into kik for over months and I lose wifi and stuff and then reconnect, How does it always keep a stable connection with the server?

**Comment by SamHoque** [comment]
Like I don't have to relogin everytime I lose wifi, How are they preventing that?

**Comment by tomer8007** [comment]
Oh I get you. I **think** they're establishing a session using a stored result of `key_from_password `. Whatever they're storing, it's enough to authenicate the user. Actually it's pretty easy to check if you have MITM running or access to the internal files the app saves.

**Comment by SamHoque** [comment]
hmm, I will take a look at where kik stores their stuff and see if they are storing the key from password

**Comment by SamHoque** [comment]
Alright so they are storing it under `CredentialData.username_passkey` So they do indeed store the passkey
