### ISSUE TITLE
Interactive client

### ISSUE THREAD

**Issue by midorlo** [tomer8007/kik-bot-api-unofficial#82]
Do you plan to implement an interactive client to this project? As KiK has no official web client I would love to be able to host my own on a private space, even even just run with from localhost on demand.

**Comment by tomer8007** [comment]
Do you mean a web client? There's a small example of an interactive console client already.

I think I've seen a partial GUI for this project, is this helpful for you?

**Comment by midorlo** [comment]
Exactly. Many communication plattforms do provide web frontends (ex. [WhatsApp](http://web.whatsapp.com/), [Threema](https://web.threema.ch/#!/welcome), [Telegram](https://web.telegram.org/#/login). Kik however doesn't. 

As it looks like you guys have already done most of the groundworks, I am curious if you plan a (web/nonweb based) frontend(, or so to say, any form of an end user friendly interactive client) as well. That said, I'd never "ask" for a story that big. No bad feelings if that is out of scope. And that said, if you know about anyone who has already build stated onto @kik-bot-api-unofficial, I'd happily follow your link as well.

**Comment by tomer8007** [comment]
I think that's quite old, but you have @Jaapp- 's  [kik-desktop](https://github.com/Jaapp-/kik-desktop) which is a nice start.

**Comment by midorlo** [comment]
That looks promising, I'll digg into it. Also I will imply that the topic ifself is out of scope for this project? Assuming this, I'll close the issue for now. Thank you for helping out. Best wishes :)

**Comment by tomer8007** [comment]
:-)
