### ISSUE TITLE
Detecting group joins

### ISSUE THREAD

**Issue by sapiosaurus** [tomer8007/kik-bot-api-unofficial#84]
Hi! Is there currently a function or callback to detect when a user joins a public group (to display things like rules, etc).

Thanks.

**Comment by tomer8007** [comment]
There isn't a callback like this right now, but what I would do if I were you is to experiment and see what XML you receive from kik when someone joins your group (you can enable DEBUG logs for this) and then filter based on that.

Additionally take a look at the [wiki page](https://github.com/tomer8007/kik-bot-api-unofficial/wiki/Message-Formats), there you can find all sorts of XML that you can when certain events happen.

**Comment by XenXenOfficial** [comment]
I've had success with `def on_group_status_received(self, response: Incoming group status):`

**Comment by tomer8007** [comment]
Nice

**Comment by XenXenOfficial** [comment]
Oops! Sorry!! It wasn't that, it was `def on_group_status_received(self, response: Incoming group status):`

**Comment by tomer8007** [comment]
Please edit your original message

**Comment by ether8unny** [comment]
shouldnt that trigger for any change in group? joins leaves promotes

**Comment by XenXenOfficial** [comment]
From my testing so far, if you include `self.check_join = True if len(data.g) > 0 else False` to the `chatting.py` file then doing 

`def on_group_status_received(self, response: chatting.IncomingGroupStatus):
     If response.check_join:
         Arguments()
`
It'll run the `Arguments()` whenever someone joins the chat

This was just to make it simpler lol 

Edit:

This was tested with leaves, promotes, demotes, bans and unbans. None gives a response except the joins.
