### ISSUE TITLE
How to handle active link

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#87]
Hello all, anybody know, how i can handle active link via sending message or handle incoming message?

**Comment by CheshireCaat** [comment]
Found
You need to do this request
https://pastebin.com/XwJ6HnPQ

**Comment by CheshireCaat** [comment]
Upd.
But I saw this request only once, although I wrote different links from different accounts, so this does not work (

**Comment by Jaapp-** [comment]
I just made a PR for that https://github.com/tomer8007/kik-bot-api-unofficial/pull/94
