### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by Kladdkaka** [tomer8007/kik-bot-api-unofficial#9]
hello!

this seems very cool, i might use it myself :) (and even contribute back if needed)

only question is, does this take care of auto register and stuff? understandable if not :)

either way thanks for making this public!

**Comment by tomer8007** [comment]
Hi!
What do you mean by auto register? Technically threre is a method called `sign_up` for automating registrations, even though from my attempts it requires captcha.

**Comment by Kladdkaka** [comment]
hi!

thanks for the fast reply, and yep, that is what I meant, thanks for letting me know, I will take a look at that method, and will let you know if I find a way to automate the captcha for that :)

**Comment by Jaapp-** [comment]
Successful account registration with captcha works now (if my current PR about it is merged and uploaded to PyPI) on kik-desktop (https://github.com/Jaapp-/kik-desktop).

**Comment by tomer8007** [comment]
That's great.
You did not use the regular expressions module, though, so I remove it.

**Comment by tomer8007** [comment]
Merged & Uploaded.

**Comment by Kladdkaka** [comment]
awesome! cheers :) ill push fixes if i find any bugs
