### ISSUE TITLE
Editing Group Information

### ISSUE THREAD

**Issue by xorist** [tomer8007/kik-bot-api-unofficial#91]
Is there currently any way to change the name of a group?

**Comment by tomer8007** [comment]
I don't see it's implemented right now, but - [here](https://github.com/tomer8007/kik-bot-api-unofficial/wiki/Message-Formats#group-adminship) you can see exactly what the XMPP format of such a request should be. So adding that to the API is definitely possible. If you do that, please submit a pull request.

**Comment by xorist** [comment]
I'm having an issue trying to add to the API. It could be that I just don't quite understand it yet. Below is my error.

> Exception in callback KikClient._on_new_data_received(b'<message fr...us></message>')
> handle: <Handle KikClient._on_new_data_received(b'<message fr...us></message>')>
> Traceback (most recent call last):
>   File "C:\Users\xorist\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\xorist\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial-0.3-py3.7.egg\kik_unofficial\client.py", line 281, in _on_new_data_received
>     self._handle_xmpp_message(xml_element)
>   File "C:\Users\xorist\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial-0.3-py3.7.egg\kik_unofficial\client.py", line 325, in _handle_xmpp_message
>     self._handle_xmlns(xmpp_message['xmlns'], xmpp_message)
>   File "C:\Users\xorist\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial-0.3-py3.7.egg\kik_unofficial\client.py", line 348, in _handle_xmlns
>     self.xml_namespace_handlers[xmlns].handle(message)
>   File "C:\Users\xorist\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial-0.3-py3.7.egg\kik_unofficial\xmlns_handlers.py", line 107, in handle
>     self.callback.on_group_status_received(IncomingGroupStatus(data))
>   File ".\GroupReplier.py", line 76, in on_group_status_received
>     self.client.change_group_name(self, "test JID", "testMessage")
> AttributeError: 'KikClient' object has no attribute 'change_group_name'

I've added the following to my client script where KikClient is defined with all it's attributes 

```
    def change_group_name(self, peer_jid: str, message: str):
        """
        Changes the name of a group.
        """
        return "testing"

```

Lastly, I've added this to my actual client controller

```
    def on_group_status_received(self, response: chatting.IncomingGroupStatus):
        print("[+] Status message in {}: {}".format(response.group_jid, response.status))
        self.client.change_group_name("test JID", "testMessage")
```

Any way I could be pointed in the right direction on what needs to happen in order to add to the API? Thanks.

**Comment by tomer8007** [comment]
Are you adding functions to `client.py` or to your own script? because you should add it to `client.py`. If you do, it looks like this should work. I'm not sure how come it says that `'KikClient' object has no attribute 'change_group_name'`. But this makes me wonder: Are your changes to `client.py` influence anything? Did you try to randomly generate syntax errors and test if it complains?

**Comment by xorist** [comment]
Yes, I'm trying to add a `change_group_name` function under the said `'KikClient'` object. In my own script I'm trying to call the function I've added and it's giving me that `no attribute 'change_group_name` error.

**Comment by tomer8007** [comment]
Do you have indication that your changes are getting used? do you edit the right `client.py` file?

**Comment by xorist** [comment]
Currently there is no indication that my changes are getting used. That could very well be the issue. I've built and installed the API using pip, where would the default `client.py` file be located? (I do not have any obscure settings for my file system environment)

**Comment by xorist** [comment]
Disregard last comment, I found it. I will update you on how the update to the API is coming along.

**Comment by xorist** [comment]
I have added the ability to change the group name to the API. It works, but it now gives me the error shown below.

```
[2018-12-09 18:22:05,128] WARNING (thread Kik Connection): [-] Received unknown xml namespace: 'kik:groups:admin', ignoring (to see full data, enable debug logs)
```
I assume this is because there is nothing yet to handle the kind of response kik gives back to the client whenever a successful change has been made to the group name. Am I correct?

**Comment by tomer8007** [comment]
Yes, it could indeed be the case. Maybe post the debug logs so we can be sure.

**Comment by SamHoque** [comment]
I don't code in python, but I believe @tomer8007 added a check for namespaces if the code doesn't have the specific namespace hardcoded it will throw that warning since it does not know how to handle it.

**Comment by tomer8007** [comment]
@LynxKik Indeed this is exactly the warning @xorist posted above.

**Comment by xorist** [comment]
@tomer8007 Attached to this comment is the portion of the debug log.
@LynxKik Thanks for that, I'll look into where I can fix this.
[log.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/2661142/log.txt)

**Comment by tomer8007** [comment]
Yes, it doesn't appear to contain useful data other than sort of an acknowledgment.

**Comment by SamHoque** [comment]
It's just a warning not an error you can just ignore it, or you can remove the line that is printing the warning altogether if you don't need to handle data that has that namespace.

**Comment by xorist** [comment]
@LynxKik Alright. I'll go ahead and get this ready to be sent up.

**Comment by xorist** [comment]
So I'm not super familiar with Git. I know how to create a new branch locally, do pulls and pushes, add and commit, etc. What's the process of getting this to you?

**Comment by xorist** [comment]
Here is the problem I'm having 

> PS C:\Users\xorist\Documents\Computers\projects\git\kik-bot-api-unofficial> git branch
> * new
> PS C:\Users\xorist\Documents\Computers\projects\git\kik-bot-api-unofficial> git add .
> warning: LF will be replaced by CRLF in kik_unofficial/callbacks.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/client.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/client_legacy.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/exceptions.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/peers.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/account.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/base_elements.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/chatting.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/errors.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/group_adminship.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/login.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/roster.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/datatypes/xmpp/sign_up.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/device_configuration.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/http/profilepics.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/protobuf/__init__.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/protobuf/group_search_service_pb2.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/utilities/cryptographics.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/utilities/parsing.py.
> The file will have its original line endings in your working directory.
> warning: LF will be replaced by CRLF in kik_unofficial/xmlns_handlers.py.
> The file will have its original line endings in your working directory.
> PS C:\Users\xorist\Documents\Computers\projects\git\kik-bot-api-unofficial> git commit -m "Added group name change abili
> ty to API"
> [new 65e90b1] Added group name change ability to API
>  3 files changed, 21 insertions(+)
> PS C:\Users\xorist\Documents\Computers\projects\git\kik-bot-api-unofficial> git push
> remote: Permission to tomer8007/kik-bot-api-unofficial.git denied to xorist.
> fatal: unable to access 'https://github.com/tomer8007/kik-bot-api-unofficial.git/': The requested URL returned error: 403
> PS C:\Users\xorist\Documents\Computers\projects\git\kik-bot-api-unofficial>

**Comment by tomer8007** [comment]
Well, this will actually be much easier if you would post the new method you created in `client.py` and I'll just commit that.

**Comment by xorist** [comment]
I've attached both of the files I had to update in order to get the API functioning with the group-name-change functionality. I've changed the filetype to txt because github won't allow .py on here, in the comments section.

[group_adminship.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/2664867/group_adminship.txt)
[client.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/2664869/client.txt)

**Comment by tomer8007** [comment]
That's great, I see you also added a feature to change the display name, password, and email. But for this I need the `account` file in the `xmpp` folder.

**EDIT**: If you still want to submit a pull request I think you need to fork this repository, then push to your GitHub, then use the UI to submit the pull request.

**Comment by xorist** [comment]
I didn't add those, that came down with the clone.
 I'll go ahead and send that, though. It's attached here.

[account.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/2664954/account.txt)

**Comment by tomer8007** [comment]
Oh sorry, I forgot about that. It's [this](https://github.com/tomer8007/kik-bot-api-unofficial/commit/80f1e6e7be2adddae1a10b91fa1ac7a6aac433f9) commit.

Anyway I pushed your feature, thanks.

**Comment by xorist** [comment]
No problem.

**Comment by xorist** [comment]
@tomer8007 Also, I really like this project and if you wouldn't mind I would be happy to work on it more frequently. I see there's a lot of stuff to be done yet. Is there any means by which I can contact you and we can talk about what you'd like to see done? Or is there a possibility I can be added to the contributors and push code I write? I have too much free-time in my afternoons and would like to have something to do in the least.

**Comment by tomer8007** [comment]
Sure you can be added to the list of contributors, it happens automatically when you submit a pull request and it's getting merged (you can also contact me by email).

I think the most wanted feature right now is sending multimedia which was discussed in [this issue](https://github.com/tomer8007/kik-bot-api-unofficial/issues/80) recently.
Also we need to solve sudden disconnects which I'm not sure why they happen.
Docstrings for new methods are also nice, etc.
