### ISSUE TITLE
Analyzing the protocol

### ISSUE THREAD

**Issue by xorist** [tomer8007/kik-bot-api-unofficial#93]
@tomer8007 I was wondering, what is your setup for analyzing the traffic between the official Kik client and it's servers? Or since you're able to get a connection going through this API do you just use that now?

**Comment by tomer8007** [comment]
I was asked this question before, see [this](https://github.com/tomer8007/kik-bot-api-unofficial/issues/5#issuecomment-342830425).

**Comment by SamHoque** [comment]
If you are a developer or know reverse engineer you can easily print out all incoming/outgoing protocol into a file by seeing where kik sends/receives their data. or if you don't know smali you can still use Xposed to do this. I wrote my self a code to print out the logs into a file using smali.

**Comment by xorist** [comment]
@LynxKik Xposed, doesn't this application require root?

**Comment by tomer8007** [comment]
@xorist It does.

**Comment by SamHoque** [comment]
Yes, It requires root and you need to flash Xposed. And create your own Xposed module that hooks into the kik logging class and prints out the variable.

**Comment by xorist** [comment]
@LynxKik @tomer8007 I don't have much experience reverse engineering android applications their selves, I might look into it. @LynxKik Is your script private? (you'd prefer not to share it?)

**Comment by xorist** [comment]
@tomer8007 [this](https://github.com/tomer8007/kik-bot-api-unofficial/issues/5#issuecomment-342830425) was helpful, thanks. (issue solved)
