### ISSUE TITLE
How to make incoming chat message listener to react only for first message from jid?

### ISSUE THREAD

**Issue by arty2203** [tomer8007/kik-bot-api-unofficial#96]
I'm currently using kind of echo bot, as simple autoresponder, but currently it responds to each incoming message. Is there any way to make listener triggered only after first incoming message from each separate jid? I've thought of fetching chat history with jid and answer if it's empty, but i suck in Python to implement that. Any ideas?

**Comment by tomer8007** [comment]
I don't know any other way to do this without fetching chat history, because otherwise you'd have to make your bot remember if it talked to this JID before or not - which means you basically track down the history yourself.

**Comment by SamHoque** [comment]
in java we could use a `Collection` to keep track of the jids., I am not sure about python

**Comment by sapiosaurus** [comment]
This isn't exactly an issue with the code so much as a request for Python help to capture that data.

If it was me, I'd connect sqlite to your bot, log the most recent chat message or history to a table and query on new messages to see if the JID exists. None of this is dependant on the API or built into it, but you can easily log messages received in the echobot example to the table/query.

Hope this helps!
