### ISSUE TITLE
socks proxy

### ISSUE THREAD

**Issue by pilipranks** [tomer8007/kik-bot-api-unofficial#99]
Hi, thank for lib, but how could I use socks proxy with kik connection?

**Comment by tomer8007** [comment]
Did you manage to get it working?

**Comment by GoodOldPhoenix** [comment]
I believe this is what you're looking for: 

```
import socks

s = socks.socksocket()
s.setproxy(socks.PROXY_TYPE_SOCKS5,"91.206.30.204",3128)
```

Put it above the connection details in /kik_unofficial/client.py
Obviously, set the IP and port to the SOCKS proxy you want to use.

**Comment by GoodOldPhoenix** [comment]
If that has worked for you, don't forget to mark your issue as closed 👍

**Comment by pilipranks** [comment]
thank, it works for me
```
socket = socks.socksocket()
if (self.socks_proxy):
     proxy=self.socks_proxy.split(':');
     socket.setproxy(socks.PROXY_TYPE_SOCKS5,proxy[0],int(proxy[1]))
socket.connect((HOST,PORT))
coro = self.loop.create_connection(lambda: self.connection, sock=socket, server_hostname=HOST, ssl=True)
```
